(function(f){var e=window.AmazonUIPageJS||window.P,k=e._namespace||e.attributeErrors,a=k?k("HLCXDetailPageAssets",""):e;a.guardFatal?a.guardFatal(f)(a,window):a.execute(function(){f(a,window)})})(function(f,e,k){f.when("A","ready").execute(function(a){a.on("a:accordion:installment-payment-buybox-accordion:select",function(d){a.$("#abbWrapper [id^\x3dmbb-offeringID-]").prop("checked",!1)})});f.when("A").register("BaseLinkKeyValuePairHelper",function(a){var d=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var c=16*Math.random()|0;return("x"===a?c:c&3|8).toString(16)})},c=function(a,c){this.key=a;this.value=c};return{getBaseLinkPairs:function(){var a=d();return{ITEM_ASSOC:new c("itemAssoc",a),UNIQ_PARENT:new c("UNIQ-itemAssoc",a),UNIQ_WARRANTY:new c("UNIQ-lnkdWrrnty",a),ITEM_ASSOC_TYPE:new c("itemAssocType","AmazonProtect"),RENDER_TYPE:new c("itemAssocRenderType","renderAll")}}}});f.when("A","BaseLinkKeyValuePairHelper").register("BaseLinkFormHelper",function(a,d){var c=a.$,r=function(a,
g){var b=0;g.find("input[id^\x3d'custom-name\\."+a+"\\.']").each(function(g,a){g=+a.name.match(/[0-9]+$/)[0];b=g>b?g:b});return b+1},p=function(a,g,b){var h=[],l=r(a,g);c.each(b,function(g,b){var c="custom-value."+a+"."+l;g=e("custom-name."+a+"."+l,b.key);b=e(c,b.value);h=h.concat([g,b]);l++});return h},e=function(a,g){var b=document.createElement("input");b.setAttribute("type","hidden");b.setAttribute("class","atcFormWarrantyData");b.setAttribute("id",a);b.setAttribute("name",a);b.setAttribute("value",
g);return b},f=function(a){a.find(".atcFormWarrantyData").each(function(a,b){b.parentNode.removeChild(b)})};return{addBaseLinkFields:function(a,g){f(g);if(!g.find("input[value\x3d'itemAssoc']").length){var b=d.getBaseLinkPairs(),h=p(1,g,[b.ITEM_ASSOC,b.UNIQ_PARENT,b.ITEM_ASSOC_TYPE]);a=p(a,g,[b.ITEM_ASSOC,b.UNIQ_WARRANTY,b.ITEM_ASSOC_TYPE,b.RENDER_TYPE]);h=h.concat(a);c.each(h,function(a,b){g.append(b)})}},removeBaseLinkFields:f,getMobileWarrantyIndex:function(a){var g=1;a.find("input[name\x3d'a']").each(function(a,
c){c.value&&(a=c.value.split("|"))&&(g=a.length)});return g+1}}});f.when("A","BaseLinkKeyValuePairHelper").register("BaseLinkDeclarativeHelper",function(a,d){var c=a.$,e=[],p=function(a){var b=!1;c.each(a,function(a,g){if("itemAssoc"===g)return b=!0,!1});return b},f=function(a,b,h){var l={},d=k(a,b);c.each(h,function(b,c){b=c.value;var h="custom-name."+a+"."+d,f="custom-value."+a+"."+d;l[h]=c.key;l[f]=b;e.push(h);e.push(f);d++});return l},k=function(a,b){var h=new RegExp("^custom-name[.]["+a+"]+[.]([0-9]+)$"),
d=0;c.each(b,function(a){if(a=a.match(h))a=+a[1],a>d&&(d=a)});return d+1},m=function(a){c.each(e,function(b,c){a[c]&&delete a[c]});e=[]};return{addBaseLinkFields:function(a){m(a);if(!p(a)){var b=d.getBaseLinkPairs(),h=f(1,a,[b.ITEM_ASSOC,b.UNIQ_PARENT,b.ITEM_ASSOC_TYPE]),b=[b.ITEM_ASSOC,b.UNIQ_WARRANTY,b.ITEM_ASSOC_TYPE,b.RENDER_TYPE],e=1;a.a&&(e=a.a.split("|").length);b=f(e+1,a,b);c.extend(a,h);c.extend(a,b)}},removeBaseLinkFields:m,getDeclarativeDataInputs:function(a){if(a=c(a)){var b=a.data("action");
if((a=a.data(b))&&a.inputs)return a.inputs}}}});"use strict";f.when("A","ready").execute(function(a){function d(a){var c=e.ue;c&&c.count&&c.count(a,(c.count(a)||0)+1)}var c=a.$;a.on("a:expander:comparison_detail_expander:toggle:expand",function(a){d("ComparisonExpanderExpanded");c(".comparison_other_attribute_row").removeClass("aok-hidden")});a.on("a:expander:comparison_detail_expander:toggle:collapse",function(a){d("ComparisonExpanderCollapsed");c(".comparison_other_attribute_row").addClass("aok-hidden")})});
f.when("A","atf","ready").execute(function(a){function d(){var c,d=a.$("#HLCXComparisonJumplink_feature_div"),e=a.$("#HLCXComparisonWidget_feature_div");c=a.$("#HLCXComparisonJumplinkContent").length?e.find("#HLCXComparisonJumplinkContent"):e.find(".HLCXComparisonJumplinkContent");e=e.has("#HLCXComparisonTable").length;d.empty();e&&c.clone().removeClass("aok-hidden").appendTo(d)}a.declarative("hlcx-send-reftag","click",function(c){a.$.get("/gp/product/ajax-handlers/reftag.html/ref\x3d"+c.data.refTag)});
d();a.on("a:pageUpdate",d)});f.when("A","ready").execute("logCsmMetricsForComparisonTabs",function(a){var d;a.on("a:tabs:comparison_items_tabs:compare_to_similar_items_tab:select a:tabs:comparison_items_tabs:compare_to_recently_viewed_items_tab:select",a.throttle(function(a){d&&d===a.selectedTab.tabName||(d=a.selectedTab.tabName,e.ue&&e.ue.count&&e.ue.count(a.selectedTab.tabName,1))},100,{trailing:!1}))});f.when("A","3p-promise","ready").register("hlcx-table-csm",function(a,d,c){function f(c){return a.$(c?
".hlcx-cmp-title-col":".comparison_image_title_cell").filter(":visible").map(function(){return a.$(this).attr("data-asin")}).toArray()}function p(){try{var a=document.cookie.match("(^|[^;]+)\\s*(session-id|sessionId)\\s*\x3d\\s*([^;]+)");return a?a.pop():""}catch(b){return""}}function k(c,b){return new d(function(d,e){function f(){b.unbind("click auxclick",f);var c=a.now()-k;a.off("DOMContentLoaded load resize scroll",n);d({timeInView:c,clickedOff:!0})}var k=a.now(),n=a.throttle(function(){if(!a.onScreen(c)){var b=
a.now()-k;a.off("DOMContentLoaded load resize scroll",n);d({timeInView:b,clickedOff:!1})}},200);b.bind("click auxclick",f);a.on("DOMContentLoaded load resize scroll",n)})}function t(a,b,c){var d=f(c);a={pageAsin:a,comparableAsins:d.slice(1),sessionId:b,deviceType:c?"mobile":"desktop"};e.ue&&e.ue.event&&e.ue.event(a,"comparison","comparison.dpTableImpression.1")}function m(c,b,d){function l(){!n&&a.onScreen(m)&&(n=!0,k(m,d()).then(function(a){n=!1;if(!(2500>a.timeInView)){var d=f(b).slice(1),h=a.timeInView,
l=++u,k;k=e.location.href.endsWith("#HLCXComparisonWidget_feature_div");a={pageAsin:c,comparableAsins:d,sessionId:q,timeInView:h,viewOnPageCounter:l,deviceType:b?"mobile":"desktop",landedOnComparisonsTable:k,clickedOff:a.clickedOff};e.ue&&e.ue.event&&e.ue.event(a,"comparison","comparison.dpTableView.2")}}))}var m=a.$(b?"#hlcx_cmp_table":"#HLCXComparisonTable");if(m.length){var q=p();t(c,q,b);var n=!1,u=0;a.on("DOMContentLoaded load resize scroll",l);a.on("a:pageUpdate",function(){c!==a.$(b?".hlcx-cmp-title-col":
".comparison_image_title_cell").first().attr("data-asin")&&a.off("DOMContentLoaded load resize scroll",l)})}}return{setupClientSideLogging:function(c,b){var d;return function(){var e=a.$(c?".hlcx-cmp-title-col":".comparison_image_title_cell").first().attr("data-asin");d!==e&&"undefined"!==typeof e&&(d=e,m(d,c,b))}}}});f.when("A","hlcx-table-csm").execute(function(a,d){d=d.setupClientSideLogging(!1,function(){return a.$("td.comparison_add_to_cart_button span.a-button, th.comparison_image_title_cell a, #comparison_sold_by_row a, #comparison_custormer_rating_row a")});
a.on("a:pageUpdate",d);d()})});
/* ******** */
(function(f){var h=window.AmazonUIPageJS||window.P,n=h._namespace||h.attributeErrors,g=n?n("DetailPageWarrantyAssets",""):h;g.guardFatal?g.guardFatal(f)(g,window):g.execute(function(){f(g,window)})})(function(f,h,n){"use strict";var g;g=function(){};"use strict";f.when("A").register("wty:Reftag",function(d){function e(a){this.prefix=a}e.prototype.log=function(a,b,k){a=k?[this.prefix,a,b,k]:[this.prefix,a,b];g("Reftag.log: "+a);a=a.join("_");d.get("/gp/product/ajax-handlers/reftag.html/ref\x3d"+a)};
return e});"use strict";f.when("A","BaseLinkFormHelper").register("wty:detailPage",function(d,e){function a(){}a.prototype.bindQuantityChange=function(b){var a=function(){b(d.$(this).val())};d.$("#quantity").bind("change",a);return a};a.prototype.unbindQuantityChange=function(b){d.$("#quantity").unbind("change",b)};a.prototype.bindBuyBoxAccordion=function(b){d.on("a:accordion:buybox-accordion:select",b);d.on("a:accordion:installment-payment-buybox-accordion:select",b);return b};a.prototype.unbindBuyBoxAccordion=
function(b){d.off("a:accordion:buybox-accordion:select",b);d.off("a:accordion:installment-payment-buybox-accordion:select",b)};a.prototype.findQuantityInput=function(b){return b.find("input[name^\x3dquantity]")};a.prototype.findOfferListingIdInput=function(b){return b.find("input[name^\x3dofferingID]")};a.prototype.handleBaselink=function(b){if(d.$("#mbb__bl").length){var a=d.$(b._checkbox[0].form);a&&(b.isChecked()?(b=b.getKvpIndex(),e.addBaseLinkFields(b,a)):e.removeBaseLinkFields(a))}};return new a});
"use strict";f.when("wty:Reftag").register("wty:MbbTypes",function(d){var e={mbb__tsn:{cssClass:"mbb__tsn",reftag:new d("psd_bb"),hasQuantity:!0},mbb__ti:{cssClass:"mbb__ti",reftag:new d("psd_ib")}};return{getType:function(a){return e[a]}}});"use strict";f.when("A","a-modal").register("wty:mbbModalHelper",function(d,e){function a(){}a.prototype.create=function(b,a,l,c){if(c){var p=d.$("#a-popover-"+a),m=p.clone(!0).prop("id","a-popover-"+a+"-Opened");p.parent().append(m)}e.create(b,{name:c?a+"-Opened":
a,header:l,width:750})};a.prototype.remove=function(a,k){e.remove(k?a+"-Opened":a)};a.prototype.hide=function(a,k){(a=e.get(k?a+"-Opened":a))&&a.hide()};return new a});"use strict";f.when("A","wty:Reftag","wty:MbbItem").register("wty:Mbb",function(d,e,a){function b(b,l,c){this._type=c;this._reftag=c.reftag;this._baseFormIndex=b;this._pageData=l;this._baseItemAsin=l.bi.a;this._mbbFeature=d.$(".mbb__bb."+c.cssClass);this._modalHeader=this._mbbFeature.find(".mbb__mh").html();this._items=[];this._reftag.log("i",
this._baseItemAsin);var e=this;this._mbbFeature.find(".mbb__r").each(function(m){var c=d.$(this),c=new a(e,c,m);e._items[m]=c})}b.prototype._destroy=function(){for(var a=0,b=this._items.length;a<b;a++)this._items[a]._destroy()};b.prototype._setQuantity=function(a){for(var b=0,c=this._items.length;b<c;b++)this._items[b]._setQuantity(a)};b.prototype._setChecked=function(a,b){for(var c=0,d=this._items.length;c<d;c++)this._items[c]._setChecked(b&&c===a)};b.prototype.getCheckedItem=function(){for(var a=
0,b=this._items.length;a<b;a++){var c=this._items[a];if(c.isChecked())return c}};b.prototype.getItems=function(){return this._items};return b});"use strict";f.when("A","wty:mbbModalHelper","wty:detailPage","a-checkbox","a-popover").register("wty:MbbItem",function(d,e,a,b,k){function l(a){a.stopPropagation();a.preventDefault()}function c(b,c,d){this._mbb=b;this._warrantyAsin=b._pageData.w[d].a;this._isSubscription=!!b._pageData.w[d].sub;this._index=d;this._row=c;this._quantity=a.findQuantityInput(c);
this._offerListingIdSelection=a.findOfferListingIdInput(c);this._checkbox=c.find("input[type\x3dcheckbox]");this._shortTitle=this._row.find(".mbb__st");this._modal=b._mbbFeature.find(".mbb__m:eq("+d+")");this._modalYes=this._modal.find(".mbb__yes");this._modalNo=this._modal.find(".mbb__no");this._modalName="MbbModal-"+this._mbb._type.cssClass+this._index;var e=this;this._onShortTitle=function(){e._logReftag("st")};this._setChecked(!1);this._logReftag("i");this._bind()}var f=d.$;c.prototype._bind=
function(){this._bindQuantity();this._bindBuyBoxAccordion();this._bindModalYes();this._bindModalNo();this._bindShortTitle();this._bindCheckbox()};c.prototype._destroy=function(){this._unbindQuantity();this._unbindBuyBoxAccordion();this._unbindModalYes();this._unbindModalNo();this._unbindShortTitle();this._unbindCheckbox()};c.prototype.getAsin=function(){return this._warrantyAsin};c.prototype.getFormIndex=function(){return this._index+this._mbb._baseFormIndex};c.prototype.getKvpIndex=function(){return this.getFormIndex()+
1};c.prototype.getOfferListingId=function(){return this._offerListingIdSelection};c.prototype.isChecked=function(){return this._checkbox.prop("checked")};c.prototype.getQuantity=function(){return this._quantity.val()};c.prototype._setChecked=function(a){this._checkbox.prop("checked",a)};c.prototype._setSubscriptionQuantityRestricted=function(a){k.remove(this._shortTitle);a?(this._bindShortTitle(),b(this._checkbox).enable(),this._row.removeClass("monthly-warranty-text-disabled"),f("#MonthlyWarrantyWarning").addClass("aok-hidden")):
(b(this._checkbox).isChecked()&&f("#MonthlyWarrantyWarning").removeClass("aok-hidden"),this._unbindShortTitle(),b(this._checkbox).uncheck(),b(this._checkbox).disable(),this._row.addClass("monthly-warranty-text-disabled"),a={inlineContent:d.$("#popover-message").data("message"),position:"triggerLeft",closeButton:"false"},k.create(this._shortTitle,a))};c.prototype._setQuantity=function(a){this._quantity.val(a)};c.prototype._logReftag=function(a){this._mbb._reftag.log(a+(this._index+1),this._mbb._baseItemAsin,
this._warrantyAsin)};c.prototype._bindModalYes=function(){var b=this;this._onModalYes=function(){b._logReftag("my");b._mbb._setChecked(b._index,!0);e.hide(b._modalName,b._isSubscription);a.handleBaselink(b)};this._modalYes.bind("click",this._onModalYes)};c.prototype._unbindModalYes=function(){this._modalYes.unbind("click",this._onModalYes)};c.prototype._bindModalNo=function(){var b=this;this._onModalNo=function(){b._logReftag("mn");b._mbb._setChecked(b._index,!1);e.hide(b._modalName,b._isSubscription);
a.handleBaselink(b)};this._modalNo.bind("click",this._onModalNo)};c.prototype._unbindModalNo=function(){this._modalNo.unbind("click",this._onModalNo)};c.prototype._bindShortTitle=function(){this._shortTitle.unbind("click",l);this._shortTitle.bind("click",this._onShortTitle);e.create(this._shortTitle,this._modalName,this._mbb._modalHeader,this._isSubscription)};c.prototype._unbindShortTitle=function(){this._shortTitle.unbind("click",this._onShortTitle);this._shortTitle.bind("click",l);e.remove(this._modalName,
this._isSubscription)};c.prototype._bindQuantity=function(){this._onQuantityChange=null;if(this._mbb._type.hasQuantity){var b=this;this._onQuantityChange=a.bindQuantityChange(function(a){b._setQuantity(a)})}};c.prototype._unbindQuantity=function(){a.unbindQuantityChange(this._onQuantityChange)};c.prototype._bindCheckbox=function(){var b=this;this._onCheckboxChange=function(){var c=b.isChecked();b._mbb._setChecked(b._index,c);b._logReftag(c?"cy":"cn");a.handleBaselink(b)};this._checkbox.bind("change",
this._onCheckboxChange)};c.prototype._unbindCheckbox=function(){this._checkbox.bind("change",this._onCheckboxChange)};c.prototype._bindBuyBoxAccordion=function(){var b=this;this._onBuyBoxAccordion=a.bindBuyBoxAccordion(function(){b._setChecked(!1);a.handleBaselink(b)})};c.prototype._unbindBuyBoxAccordion=function(){a.unbindBuyBoxAccordion(this._onBuyBoxAccordion)};return c});"use strict";f.when("A","wty:MbbTypes","wty:Mbb","ready").register("mbb",function(d,e,a){function b(){this._mbbs={}}var f=new b;
d.on("mbb:loaded",function(b,c,g){var m=e.getType(g);if(m){var h=f._mbbs[g];h&&h._destroy();h=new a(b,c,m);f._mbbs[g]=h;d.trigger("mbb:ready",g)}});b.prototype.getMbb=function(a){return this._mbbs[a]};return f})});
/* ******** */
(function(l){var p=window.AmazonUIPageJS||window.P,B=p._namespace||p.attributeErrors,b=B?B("DetailPageAlohaAssets",""):p;b.guardFatal?b.guardFatal(l)(b,window):b.execute(function(){l(b,window)})})(function(l,p,B){l.when("A","a-modal","a-checkbox","aloha-simplebundle-common","ready").execute(function(b,p,l,k){function y(){b.declarative("show-review-tab","click",function(g){b.$(g.$target).closest(a.AUI_PAGE_ROOT).find(".popoverReviewsTab").click()});b.declarative("add-to-cart","click",function(g){b.$(a.SB_ROOT+
" "+a.SB_BUYBOX_ITEM_CHECKBOX+" "+a.INPUT_TYPE_CHECKBOX).filter(function(){return b.$(this).data("asin")===g.data.asin}).prop("checked",!0).change();b.$("[id^\x3dpopover-simpleBundle-]").each(function(){var a=p.get(b.$(this));a.isActive()&&a.hide()})});b.declarative("focus-image","mouseenter",function(b){var f=b.$target,k=f.parents(a.AUI_PAGE_ROOT);b=b.data;k.find("#productImageMain-"+b.asin).attr("src",b.imageUrl);k.find(".thumbnail-group").removeClass("a-button-selected");k.find("#"+f.prop("name")).addClass("a-button-selected")})}
var a={BUYBOX_ACCORDION:"#buyBoxAccordion",ADD_TO_CART_FORM:"#addToCart",ADD_TO_CART_ATTACH_BUTTON:"#add-to-cart-button.attach-dss-atc:button",SESSION_ID:"#session-id",OFFER_LISTING_ID:"#offerListingID",AUI_MODAL_SCROLLER:".a-modal-scroller",AUI_PAGE_ROOT:"#a-page",INPUT_TYPE_CHECKBOX:"input[type\x3d'checkbox']",BASE_PRODUCT_PRICE:"#base-product-price",BASE_PRODUCT_PRICE_DATA:"base-product-price",SB_ROOT:".showBundleAsins.simpleBundleFeatureContainer",SB_EXPANDED_MODAL_EXPANDER_HEADER_PREFIX:".simple-bundle-item-expand-header-",
SB_EXPANDED_MODAL_EXPANDER_CONTENT_PREFIX:".simple-bundle-item-expander-content-",SB_EXPANDED_MODAL_LINK:".simple-bundle-buybox-expanded-modal-link",SB_EXPANDED_MODAL_ITEM_LINK_PREFIX:".simple-bundle-item-link-",SB_ACCESSORY_ITEM_LINK_PREFIX:".popover-simpleBundle-link-",SB_BUYBOX_ITEM_CHECKBOX:".simple-bundle-buybox-item-checkbox",SB_BUYBOX_CHECKBOX_PREFIX:".simple-bundle-item-",SB_EXPANDED_CHECKBOX_PREFIX:".simple-bundle-modal-item-",SB_EXPANDER_TITLE:".aloha-simple-bundle-expand-header-title"},
f=!1,n=b.debounce(function(){var g=b.$(a.SB_ROOT);if(g.length){var h=b.$(a.ADD_TO_CART_FORM),n=h.find(":submit").length&&h.find(a.OFFER_LISTING_ID).val(),p=b.$(a.ADD_TO_CART_ATTACH_BUTTON),l=p.length;if(n||l){y();var q=k.getSimpleBundlePageState()||{},x=q.expandedBuyboxEnabled,H=q.selectionMode||"SINGLE",c=q.items||[],A=[],t=b.$(a.SESSION_ID).val(),F=g.find(a.SB_EXPANDED_MODAL_LINK),m,e={baseAsin:q.baseAsin,marketplaceId:q.marketPlaceId,baseItemPrice:b.$(a.BASE_PRODUCT_PRICE).data(a.BASE_PRODUCT_PRICE_DATA),
clientType:"aloha-simplebundle-desktop",currencyOfPreferenceSupported:q.currencyOfPreferenceSupported||!1},u=k.createMetricsLogger(e);f||(f=!0,b.defer(function(){u.logNexusImpression(c);u.logImpressionRefTag()}));F.click(function(b){b.originalEvent&&u.logExpandedLink()});c.forEach(function(e,d){function c(){var e=!1;h.click(function(){e=!e});g.find(a.SB_EXPANDED_MODAL_ITEM_LINK_PREFIX+d).click(function(){e||h.click();F.click();m=m||b.$(a.AUI_MODAL_SCROLLER);m.scrollTop(h.offset().top-m.offset().top+
m.scrollTop())})}function f(){var c=g.find(a.SB_EXPANDED_MODAL_EXPANDER_CONTENT_PREFIX+d),I="/gp/product/features/aloha-ppd/udp-ajax-handler/minidp.html?asin\x3d"+e.asin+"\x26marketplaceId\x3d"+q.marketPlaceId+"\x26offerId\x3d"+e.offerListingId+"\x26activeTab\x3d0",m="a:expander:simple-bundle-item-expander-"+d+":toggle",x=b.once(function(){c.load(I,null,function(e,a,d){b.$.trim(c.html())?(c.find(".a-span-last \x3e .a-spacing-top-base").remove(),c.find(".popover-add-to-cart-button").remove(),e=c.find("#a-page \x3e div \x3e div.a-row"),
a=c.find(".popover-in-stock"),a.remove(),a.addClass("aloha-simple-bundle-modal-detailed-info-header-row-text"),e.append(a),a=c.find(".popover-ship-sold-by"),a.remove(),a.addClass("aloha-simple-bundle-modal-detailed-info-header-row-text"),e.append(a),a=c.find(".popover-retail-domain"),a.remove(),e.append(a),e=c.find("#a-page \x3e div \x3e div.a-column.a-span9"),e.removeClass("a-span9"),e.addClass("a-span12")):c.text(q.ajaxFailMsg)})}),w=m+":expand";b.off(w);b.on(w,function(e){u.logItemLink(d);h.find(a.SB_EXPANDER_TITLE).removeClass("aloha-simple-bundle-expand-header-title-truncate");
b.$.trim(c.html())||x()});m+=":collapse";b.off(m);b.on(m,function(e){h.find(a.SB_EXPANDER_TITLE).addClass("aloha-simple-bundle-expand-header-title-truncate")})}var h=g.find(a.SB_EXPANDED_MODAL_EXPANDER_HEADER_PREFIX+d);if(x)c(),f();else{var n=g.find(a.SB_ACCESSORY_ITEM_LINK_PREFIX+d);n.unbind("click.MiniDpClickHandler");n.bind("click.MiniDpClickHandler",function(){u.logItemLink(d);u.logNexusOpenMiniDP(d,e);u.logMiniDPRefTag(d)})}k.setupCheckboxes(A,d,x,e.asin,q.maxBuyboxItemsDesktop,a.SB_BUYBOX_CHECKBOX_PREFIX+
d+" "+a.INPUT_TYPE_CHECKBOX,a.SB_EXPANDED_CHECKBOX_PREFIX+d+" "+a.INPUT_TYPE_CHECKBOX,a.SB_BUYBOX_CHECKBOX_PREFIX+d,a.SB_EXPANDED_CHECKBOX_PREFIX+d,H)});e=b.$(a.BUYBOX_ACCORDION);e.length?e.children().each(function(){h=b.$(this).find(a.ADD_TO_CART_FORM);var e=h.find(a.ADD_TO_CART_ATTACH_BUTTON),d=e.length,q=h.find(a.SB_ROOT).length,m=h.find(":submit").length&&h.find(a.OFFER_LISTING_ID).val();q&&m&&k.setupAddToCart(h,A,c,u,t,x);d&&k.setupAddToCartForButton(e,A,c,u,t,x,h)}):(n&&k.setupAddToCart(h,A,
c,u,t,x),l&&k.setupAddToCartForButton(p,A,c,u,t,x,h))}else g.hide()}},200);n();b.on("a:pageUpdate",n);b.on("attach:dss:initialized",function(){b.off("a:pageUpdate",n);n()})});"use strict";l.when("A","a-checkbox","aloha-uatc","aloha-buy-now-integration","aloha-buybox-form-util").register("aloha-simplebundle-common",function(b,v,D,k,y){function a(a,f){var h=b.$(a);h.change(function(){h.prop("checked",this.checked)});var c=b.$(f);c.length||(c=h);return{$element:h,$container:c,api:v(a),show:function(){c.hasClass(z.AUI_HIDDEN)&&
c.removeClass(z.AUI_HIDDEN);c.show()},hide:function(){c.hasClass(z.AUI_HIDDEN)||c.addClass(z.AUI_HIDDEN)},isVisible:function(){return!c.hasClass(z.AUI_HIDDEN)}}}function f(a,b,h){b.forEach(function(b){a.addItem(b.asin,b.offerListingId,b.quantity);h.logCheckboxSelected(b.index,b.quantity);h.logAddToCartRefTag(b.index)})}function n(b,a,h){var c=[],f=[];a.forEach(function(a,g){var m=b[g];a.api.isChecked()?c.push({asin:m.asin,offerListingId:m.offerListingId,ourPrice:m.ourPrice,ourPriceAmount:m.ourPriceAmount,
ourPriceSymbol:m.ourPriceSymbol,ourPriceCode:m.ourPriceCode,index:g,quantity:h}):f.push({asin:m.asin,ourPrice:m.ourPrice,ourPriceAmount:m.ourPriceAmount,ourPriceSymbol:m.ourPriceSymbol,ourPriceCode:m.ourPriceCode,index:g,isVisible:a.isVisible()})});return{selectedLineItems:c,unselectedItems:f}}var g=/[^\d,\.]/g,h=/,/g,E=/\./g,G=/(^\D+|\D+$)/,z={AUI_HIDDEN:"aok-hidden"};return{createMetricsLogger:function(a){function f(a,b){p.ue&&p.ue.count&&p.ue.count("aloha-simplebundle-"+a,b)}function n(){var e;
e=a.currencyOfPreferenceSupported?{priceFormatted:a.baseItemPrice,priceDecimal:null,currencySymbol:null}:l(a.baseItemPrice);return{baseAsin:a.baseAsin,baseItemPrice:e.priceFormatted,baseItemCurrencySymbol:e.currencySymbol,baseItemPriceDecimal:e.priceDecimal,clientType:a.clientType,feature:"abb"}}function c(e,b){p.ue&&p.ue.event&&(e.requestId=m,e.producerId="atch",e.obfuscatedMarketplaceId=a.marketplaceId,p.ue.event(e,"atch",b,{ssd:!0}))}function k(a){b.ajax("/gp/product/ajax-handlers/reftag.html?ref_\x3d"+
a,{method:"get"})}function t(b){return a.currencyOfPreferenceSupported?{priceFormatted:b.ourPrice,priceDecimal:parseFloat(b.ourPriceAmount)||null,currencySymbol:b.ourPriceSymbol}:l(b.ourPrice)}function l(a){a=a||"";var b=a.lastIndexOf(","),c=a.lastIndexOf("."),d;b>c?(c=E,d=h):(c=h,d=E);(b=a.match(G))&&(b=b[0].trim());c=a.replace(g,"").replace(c,"").replace(d,".");c=parseFloat(c);return{priceFormatted:a,currencySymbol:b,priceDecimal:c}}var m=Date.now().toString(10)+Math.random().toString(16).substring(2,
13);b.defer(function(){f("view",1)});return{logAddToCart:function(a){f("addtocart",a)},logExpandedLink:function(){f("buybox-expanded-link",1)},logCheckboxSelected:function(a,b){f("checkbox-"+(a+1),b)},logItemLink:function(a){f("link-"+(a+1),1)},logImpressionRefTag:function(){k("dp_atch_abb_i")},logAddToCartRefTag:function(a){k("dp_atch_abb_atc_"+(a+1))},logMiniDPRefTag:function(a){k("dp_atch_abb_smdp_"+(a+1))},logNexusImpression:function(a){var b=n();b.accessories=a.map(function(a,b){var c=t(a);return{asin:a.asin,
displayPosition:b+1,price:c.priceFormatted,currencySymbol:c.currencySymbol,priceDecimal:c.priceDecimal}});c(b,"attach.ABBImpression.5")},logNexusAddBaseToCart:function(a,b,f){var d=n();d.baseQuantity=Number(f);d.accessoriesAdded=a.map(function(a){var b=t(a);return{asin:a.asin,displayPosition:a.index+1,quantity:Number(a.quantity),price:b.priceFormatted,currencySymbol:b.currencySymbol,priceDecimal:b.priceDecimal}});d.accessoriesNotAdded=b.map(function(a){var b=t(a);return{asin:a.asin,displayPosition:a.index+
1,price:b.priceFormatted,currencySymbol:b.currencySymbol,priceDecimal:b.priceDecimal}});c(d,"attach.ABBAddBaseToCart.9")},logNexusOpenMiniDP:function(a,b){var f=t(b),d=n();d.accessoryAsin=b.asin;d.accessoryDisplayPosition=Number(a)+1;d.accessoryPrice=f.priceFormatted;d.accessoryItemCurrencySymbol=f.currencySymbol;d.accessoryItemPriceDecimal=f.priceDecimal;c(d,"attach.ABBShowMiniDP.4")}}},getSimpleBundlePageState:function(){var a=b.$(".simpleBundleJavascriptParameters").find("script").html();return b.parseJSON(a)},
getCheckboxCollectionObject:a,setupAddToCart:function(a,h,g,c,l,t){function v(a,r){if(m){var d=b.$(a.currentTarget);if(k.isBuyNow(d)){var q=t?1:e.find("*[name\x3d'quantity']").val()||1,w=n(g,h,q);k.checkoutWith(w.selectedLineItems,d)}else return}var C=D.createAddToCartRequest(l,function(){r()},function(){p.ueLogError&&p.ueLogError({message:"[There was an error while adding items to the cart using the universal add to cart api.]"},{logLevel:"ERROR",attribution:"SimpleBundle"});r()}),q=t?1:e.find("*[name\x3d'quantity']").val()||
1,w=n(g,h,q);f(C,w.selectedLineItems,c);d=w.unselectedItems.filter(function(a){return a.isVisible});c.logNexusAddBaseToCart(w.selectedLineItems,d,q);q=C.count();0!==q&&(d=b.$(a.currentTarget),k.isBuyNow(d)?k.checkoutWith(w.selectedLineItems,d):(m=!0,a.preventDefault(),c.logAddToCart(q),C.call()))}var m=!1,e=a;a.unbind("submit.SimpleBundleSubmitHandler");a.bind("submit.SimpleBundleSubmitHandler",function(a){var c=b.$(this);v(a,function(){c.submit()})});a.find(":submit").unbind("click.SBB");a.find(":submit").bind("click.SBB",
function(a){var c=b.$(this),d=c.closest(".a-accordion-row-container");d.length&&(e=d,v(a,function(){c.click()}))})},setupAddToCartForDeclarative:function(a,b,h,c,g,k,v){a.unbind("click.SimpleBundleClickHandler");a.bind("click.SimpleBundleClickHandler",function(a){a=D.createAddToCartRequest(g,function(){l.now("attach-external-atc-interceptor").execute(function(a){a&&q.selectedLineItems.forEach(function(b){a.updateAttachModule(b.asin)})})},function(){p.ueLogError&&p.ueLogError({message:"[There was an error while adding items to the cart using the universal add to cart api.]"},
{logLevel:"ERROR",attribution:"SimpleBundle"})});var e=k?1:v.find("*[name\x3d'quantity']").val()||1,q=n(h,b,e);f(a,q.selectedLineItems,c);var r=q.unselectedItems.filter(function(a){return a.isVisible});c.logNexusAddBaseToCart(q.selectedLineItems,r,e);if(e=a.count())c.logAddToCart(e),a.call()})},setupCheckboxes:function(b,f,h,c,g,k,n,m,e,l){var r=a(k,m);b.push(r);r.api.enable();r.$element.data("asin",c);if(h){var d=a(n,e);d.api.enable();d.api.check(r.api.isChecked());d.$element.change(function(){var a=
d.api.isChecked();r.api.check(a)});r.$element.change(function(){var a=r.api.isChecked();d.api.check(a);var c=0;b.forEach(function(a){c<g&&a.api.isChecked()?(c++,a.show()):a.hide()});c<g&&b.forEach(function(a){c<g&&a.api.isUnchecked()&&(c++,a.show())})})}else"SINGLE"===l&&r.$element.change(function(){r.api.isChecked()&&b.forEach(function(a,b){f!==b&&a.api.uncheck()})});0<b.length&&b[0].$element.change()},setupAddToCartForButton:function(a,f,h,c,g,k,p){function m(){var a=k?1:e.find("*[name\x3d'quantity']").val()||
1,b=n(h,f,a);y.addItems(p,b.selectedLineItems,c);var d=b.unselectedItems.filter(function(a){return a.isVisible});l.now("attach-external-atc-interceptor").execute(function(a){a&&b.selectedLineItems.forEach(function(b){a.updateAttachModule(b.asin)})});c.logNexusAddBaseToCart(b.selectedLineItems,d,a);c.logAddToCart(b.selectedLineItems.length)}var e=p;a.unbind("click.button.SBB");a.bind("click.button.SBB",function(){var a=b.$(this).closest(".a-accordion-row-container");a.length&&(e=a);m()})}}});"use strict";
l.when("A").register("aloha-uatc",function(b){function l(p,k,v,a,f){var n=0;f=f||5E3;a=a||v;var g={clientName:"AmazonWireless"};g.verificationSessionID=p;return{count:function(){return n},call:function(){n&&b.post("/gp/add-to-cart/json",{timeout:f,params:g,success:k,error:v,abort:a})},addItem:function(a,b,f){g["ASIN."+n]=a;g["offerListingID."+n]=b;g["quantity."+n]=f||1;n++}}}return{createAddToCartRequest:l,createSingleFinalCallbackAddToCartRequest:function(b,k){return l(b,k,k,k)}}});"use strict";
l.when("ready").register("aloha-buy-now-integration",function(){var b={};l.when("turbo-checkout-buy-now-integration").execute(function(l){b=l});return{isBuyNow:function(l){return"function"===typeof b.isBuyNow&&b.isBuyNow(l)},checkoutWith:function(l,p){return b.checkoutWith(l,p)}}});"use strict";l.when("A").register("aloha-buybox-form-util",function(b){function l(a){for(var b=2;0<a.find('input[name\x3d"asin.'+b+'"]').length||0<a.find('input[name\x3d"offeringID.'+b+'"]').length;)b++;return b}function p(a,
b){for(;0<a.find('input[name\x3d"asin.'+b+'"]').length||0<a.find('input[name\x3d"offeringID.'+b+'"]').length;)b++;return b}function k(a,f){return[b.$("\x3cinput /\x3e",{type:"hidden",name:"asin."+f,value:a.asin,class:"aloha-accessory-form-input"}),b.$("\x3cinput /\x3e",{type:"hidden",name:"offeringID."+f,value:a.offerListingId,class:"aloha-accessory-form-input"}),b.$("\x3cinput /\x3e",{type:"hidden",name:"quantity."+f,value:a.quantity||1,class:"aloha-accessory-form-input"})]}var y=[];b.on("aloha:detailPage:reappear",
function(){y=[];b.$(".aloha-accessory-form-input").remove()});return{addItems:function(a,b,n){var g=l(a);b.forEach(function(b){if(b!==B&&b.asin&&b.offerListingId){g=p(a,g);var f=k(b,g);f.forEach(function(b){a.append(b)});y.push(f);g++;n&&(n.logCheckboxSelected(b.index,b.quantity),n.logAddToCartRefTag(b.index))}});b=a.find('input[name\x3d"itemCount"]');0===b.length?a.append('\x3cinput type\x3d"hidden" name\x3d"itemCount" value\x3d"'+g+'"\x3e'):b[0].value=g}}})});
/* ******** */
(function(k){var l=window.AmazonUIPageJS||window.P,u=l._namespace||l.attributeErrors,a=u?u("DetailPageAttachAssets",""):l;a.guardFatal?a.guardFatal(k)(a,window):a.execute(function(){k(a,window)})})(function(k,l,u){"use strict";k.when("A").register("attach-variant-registration",function(a){var c={};return{registerVariantFlag:function(a){if(c.hasOwnProperty(a))throw"Variant flag already registered";c[a]=!0},getVariantFlag:function(a){return c.hasOwnProperty(a)}}});"use strict";k.when("attach-variant-registration").execute(function(a){a.registerVariantFlag("ATTACH_ASSETS_CONSOLIDATED_WEBLAB_TRIGGERING_253364_253365")});
"use strict";k.when("A").register("attach-baselink",function(){var a=null;k.when("BaseLinkFormHelper").execute(function(c){a=c});return{createBaseLinkFormFields:function(c,f){return a?a.addBaseLinkFields(c,f):null}}});"use strict";k.when("A").register("attach-external-atc-interceptor",function(a){var c=a.$,f=[],d=[],h=!1,r=!1,b=function(){r=!0},m=function(a){var b=d.indexOf(a);-1<b&&(a=c("#attach_add_accessory_alert_"+b),b=c("#attach_add_accessory_button_"+b),a&&b&&(a.removeClass("aok-hidden"),b.addClass("aok-hidden")))};
return{updateAttachModule:function(a){b&&(h?m(a):f.push(a))},loadAttachModule:function(a){if(r)for(h=!0,d=a;0<f.length;)a=f.shift(),m(a)},unloadAttachModule:function(){h=!1;d=[]},enableModule:b}});"use strict";k.when("A").register("attach-preinitiate-checkout",function(a){return{getCartInitiateId:function(){return(new Date).getTime()},preinitiateCheckout:function(c){var f;f=a.$("#attach-desktop-sideSheet");var d=a.$("#attach_accessory_sheet");f=f.length?f:d;f.find("iframe#checkoutPrefetch").remove();
c="/gp/cart/checkout-prefetch.html?\x26cartInitiateId\x3d"+c;d=document.createElement("iframe");d.setAttribute("src",c);d.setAttribute("style","width:0px;height:0px;display:none;position:absolute;");d.setAttribute("name","checkoutPrefetch");d.setAttribute("id","checkoutPrefetch");f.append(d)}}});"use strict";k.when("A","attach-common","attach-variant-registration").register("attach-weblabs",function(a,c,f){function d(b){var c=a.$(b).val();b=[];if(c&&0<c.length)for(var c=c.slice(1,-1).split(","),d=
0;d<c.length;d++){var e=c[d].trim();0<e.length&&b.push(e)}return b}var h={},r=h.Selectors={CORE_FREE_SHIPPING_MESSAGE:"#attach-core-free-shipping-message",CLIENT_SIDE_ATTACH_WEBLABS:"#attach-weblabsToTriggerClientSide",CLIENT_SIDE_EMPTY_ASIN_LIST_WEBLABS:"#attach-weblabsToTriggerClientSideWhenEmptyAsinList",SHOW_ACCESSORY_COUPONS_DSS:"#attach-accessory-coupons-dss",SHOW_ACCESSORY_COUPONS_MBS:"#attach-accessory-coupons-mbs"};h.isShowAccessoryCouponsDssEnabled=function(){return c.elementExists(r.SHOW_ACCESSORY_COUPONS_DSS)};
h.isShowAccessoryCouponsMbsEnabled=function(){return c.elementExists(r.SHOW_ACCESSORY_COUPONS_MBS)};h.isCoreFreeShippingMessageEnabled=function(){return c.elementExists(r.CORE_FREE_SHIPPING_MESSAGE)};h.isInstallmentsDssIntegrationEnabled=function(){return f.getVariantFlag("DP_INSTALLMENTS_DSS_231673:T1")};h.isInstallmentsOnMbsEnabled=function(){return f.getVariantFlag("DP_INSTALLMENTS_ON_MBS_241566:T1")};h.isWeblabTriggeringConsolidationEnabled=function(){return f.getVariantFlag("ATTACH_ASSETS_CONSOLIDATED_WEBLAB_TRIGGERING_253364_253365")};
h.isAttachDebugParametersEnabled=function(){return f.getVariantFlag("ATTACH_DEBUG_PARAMS_266682")};h.getWeblabsToTriggerClientSide=function(){return d(r.CLIENT_SIDE_ATTACH_WEBLABS)};h.getWeblabsToTriggerClientSideForEmptyAsinList=function(){return d(r.CLIENT_SIDE_EMPTY_ASIN_LIST_WEBLABS)};h.getAllWeblabsToTriggerClientSide=function(){return h.getWeblabsToTriggerClientSide().concat(h.getWeblabsToTriggerClientSideForEmptyAsinList())};h.triggerClientSideWeblabs=function(b){b=b||[];b=b.concat(h.getAllWeblabsToTriggerClientSide());
0<b.length&&(b=a.$.param({weblabs:b},!0),a.$.post("/gp/product/features/aloha-ppd/getTreatmentAndRecordWeblabs.html",b))};return h});"use strict";k.when("A").register("attach-logging",function(a){var c={},f,d,h;c.NEXUS={PRODUCER_ID:"atch",ACCESSORY_IMPRESSIONS_PREFIX:"attach.AccessoryImpressions.",ACCESSORY_IMPRESSIONS_SCHEMA_VERSION:"7",ADD_ACCESSORY_PREFIX:"attach.AddAccessoryToCart.",ADD_ACCESSORY_SCHEMA_VERSION:"12",ADD_WARRANTY_PREFIX:"attach.AddWarrantyToCart.",ADD_WARRANTY_SCHEMA_VERSION:"5",
WARRANTY_IMPRESSION_PREFIX:"attach.WarrantyImpression.",WARRANTY_IMPRESSION_SCHEMA_VERSION:"6",DSS_WARNING_MESSAGE_PREFIX:"attach.DssWarningMessages.",DSS_WARNING_MESSAGE_VERSION:"2",PROMOTION_CLAIMED_PREFIX:"attach.ClaimPromotion.",PROMOTION_CLAIMED_SCHEMA_VERSION:"2",ACCESSORY_TYPE:{ACCESSORY:"accessory",WARRANTY:"warranty"}};c.FEATURES={DSS:"dss"};c.REF_TAGS={WARRANTY_IMPRESSION:"dp_atch_dss_w_i_",WARRANTY_ADD_TO_CART:"dp_atch_dss_w_y_"};c.initialize=function(a,b){f=a;d=b};c.setPayloadBuilder=
function(a){h=function(){var b=a();b.feature=f;b.obfuscatedMarketplaceId=d||l.ue_mid;b.producerId=c.NEXUS.PRODUCER_ID;b.requestId=c.getRandomHexString();return b}};c.getRandomHexString=function(){return Date.now().toString(10)+Math.random().toString(16).substring(2,13)};c.log=function(a,b){l.ue&&l.ue.event&&l.ue.event(a,c.NEXUS.PRODUCER_ID,b,{ssd:!0})};c.logAccessoryAddToCart=function(a){var b=c.NEXUS.ADD_ACCESSORY_PREFIX+c.NEXUS.ADD_ACCESSORY_SCHEMA_VERSION,d=h();d.type=c.NEXUS.ACCESSORY_TYPE.ACCESSORY;
d.displayPosition=parseInt(a.index)+1;d.accessoryAsin=a.asin;d.accessoryAsinPrice=a.priceFormatted;d.accessoryItemCurrencySymbol=a.currencySymbol;d.accessoryItemPriceDecimal=a.priceDecimal;d.couponType=a.couponType;d.couponDecimal=a.couponDecimal;c.log(d,b)};c.logAccessoryImpressions=function(a){var b=c.NEXUS.ACCESSORY_IMPRESSIONS_PREFIX+c.NEXUS.ACCESSORY_IMPRESSIONS_SCHEMA_VERSION,d=h();d.accessories=[];for(var f=0;f<a.length;f++){var e=a[f];d.accessories.push({displayPosition:parseInt(e.index)+
1,asin:e.asin,price:e.priceFormatted,currencySymbol:e.currencySymbol,priceDecimal:e.priceDecimal,couponType:e.couponType,couponDecimal:e.couponDecimal})}c.log(d,b)};c.logWarrantyAddToCart=function(a){var b=c.NEXUS.ADD_WARRANTY_PREFIX+c.NEXUS.ADD_WARRANTY_SCHEMA_VERSION,d=h();d.asin=a.asin;d.price=a.priceFormatted;d.warrantyCurrencySymbol=a.currencySymbol;d.warrantyPriceDecimal=a.priceDecimal;c.log(d,b);c.logWarrantyRefTag(c.REF_TAGS.WARRANTY_ADD_TO_CART,a.asin)};c.logWarrantyImpression=function(a){var b=
c.NEXUS.WARRANTY_IMPRESSION_PREFIX+c.NEXUS.WARRANTY_IMPRESSION_SCHEMA_VERSION,d=h();d.asin=a.asin;d.price=a.priceFormatted;d.warrantyCurrencySymbol=a.currencySymbol;d.warrantyPriceDecimal=a.priceDecimal;c.log(d,b);c.logWarrantyRefTag(c.REF_TAGS.WARRANTY_IMPRESSION,a.asin)};c.logWarrantyRefTag=function(c,b){var d=h().baseAsin;a.get("/gp/product/ajax-handlers/reftag.html?ref_\x3d"+(c+d+"_"+b))};c.logSecondarySheetRefTag=function(c){var b=h().baseAsin;a.get("/gp/product/ajax-handlers/reftag.html?ref_\x3d"+
(c+"_"+b))};c.logMapleError=function(){l.ue&&l.ue.count&&l.ue.count("MAPLE::DSS::Error",(l.ue.count("MAPLE::DSS::Error")||0)+1)};c.logCount=function(a,b){l.ue&&l.ue.count&&(b=b||1,l.ue.count(a,(l.ue.count(a)||0)+b))};c.logDSSWarningMessage=function(a){var b=c.NEXUS.DSS_WARNING_MESSAGE_PREFIX+c.NEXUS.DSS_WARNING_MESSAGE_VERSION,d=h();c.log({quantity:d.quantity.toString(),baseAsin:d.baseAsin,warningMessage:a},b)};c.logPromotionClaimed=function(a){var b=c.NEXUS.PROMOTION_CLAIMED_PREFIX+c.NEXUS.PROMOTION_CLAIMED_SCHEMA_VERSION,
d=h();d.asin=a.asin;d.accessoryCurrencySymbol=a.currencySymbol;d.accessoryPriceDecimal=a.priceDecimal;d.displayPosition=a.index+1;null!==a.couponType&&(d.promoDecimal=a.couponDecimal,d.promoDecimalType=a.couponType,d.promoType="coupon");c.log(d,b)};return c});"use strict";k.when("A","attach-logging").register("attach-maple",function(a,c){var f={},d;f.initialize=function(){d=!1};f.loadBannerHTML=function(){var f=a.$.Deferred(),l={};d&&(l.cart=null);a.post("/gp/cobrandcard/dss-maple-banner.html",{params:l,
success:function(a){f.resolve(a)},error:function(){c.logMapleError();f.resolve(null)}});return f.promise()};f.suppressMathBox=function(){d=!0};f.updateMathBox=function(a){"undefined"!==typeof mapleMathBox&&null!==mapleMathBox&&mapleMathBox.updateMapleMath({totalCost:a})};return f});"use strict";k.when("A","attach-variant-registration").register("attach-common",function(a,c){var f={FailureModes:{ERROR_500:1,RESUBMIT_BUY_BOX:2,TRANSITION_TO_HUC:3}};c=f.Selectors={ADD_TO_CART_BUTTON:"#add-to-cart-button"};
f.buyButton=a.$(c.ADD_TO_CART_BUTTON);f.reject=function(c,h){return f.rejectPromise(a.$.Deferred(),c,h)};f.rejectPromise=function(c,f,k){if(k&&k.count&&l.ue&&l.ue.count)if("string"===typeof k.count)l.ue.count(k.count,1);else if(a.$.isArray(k.count))for(var b=0;b<k.count.length;b++)l.ue.count(k.count[b],1);return c.reject(f,k)};f.pipeJSON=function(a){try{return JSON.parse(a)}catch(c){return f.reject(null,{count:"ATTACH_DSS_JSON_PARSE_FAILURE"})}};f.unescapeJson=function(a){if(!a)return null;a=a.replace(/\|\|/g,
'"');return a=a.replace(/&pipe;/g,"||")};f.elementExists=function(c){return c?c instanceof a.$?0!==c.length:0!==a.$(c).length:!1};f.moduleExists=function(c){return(c=a.$("#"+c+"_feature_div").html())?0<c.trim().length:!1};f.isCurrencyOfPreferenceApplied=function(){return"true"===a.$("#attach-used-currency-of-preference").val()};f.hasWarranty=function(){return 0<a.$("#warrantyEscapedJson").length};f.submitATCForm=function(){var c=f.getAtcForm().serialize(),c=a.$.post("/gp/product/handle-buy-box/ref\x3ddp_start-bbf_1_glance",
c);c.fail(function(){l.ue&&l.ue.count&&l.ue.count("ATTACH_DSS_ADD_BASE_FAILURE",1)});a.trigger("attach:add-base-to-cart",c)};f.getAtcForm=function(){return f.buyButton.closest("form")};return f});"use strict";k.when("A","attach-common","attach-logging","attach-baselink","attach-weblabs","attach-variant-registration").register("attach-desktop-warranty-pane",function(a,c,f,d,h,k){var b={name:"warranty"},m=b.Selectors={ASIN:"#attach-warranty-asin",PRICE_FORMATTED:"#attach-accessory-price-warranty",PRICE_AMOUNT:"#attach-accessory-price-warranty-amount",
BASE_ASIN:"#ASIN",BASE_CURRENCY_SYMBOL:"#attach-base-product-currency-symbol",ATC_QUANTITY:"#quantity",ATC_WARRANTY:".attach-warranty-input",JSON_DATA:"#warrantyEscapedJson",PANE:"#attach-warranty-pane",PANE_IMAGE:"#attach-sheet-warranty-image",PANE_UPSELL_IMAGE:"#attach-sheet-warranty-upsell-image",PANE_ADD_BUTTON:"#attachSiAddCoverage",PANE_NO_BUTTON:"#attachSiNoCoverage",PANE_WARRANTY_TITLE:"#attach-warranty-displayTitle"};b.getWarrantyLoggingPayload=function(){var b=a.$(m.ASIN).val(),e=a.$(m.PRICE_FORMATTED),
d=a.$(m.PRICE_AMOUNT);return c.elementExists(d)?{asin:b,priceFormatted:e.text().trim(),priceDecimal:parseFloat(d.val())||null,currencySymbol:a.$(m.BASE_CURRENCY_SYMBOL).val()||null}:{asin:b,priceFormatted:e.text().trim(),priceDecimal:null,currencySymbol:null}};b.appendWarrantyToATCForm=function(b,e){if(a.$(m.BASE_ASIN).val()&&b&&e){var f=c.getAtcForm();f.append('\x3cinput type\x3d"hidden" id\x3d"useABBHandler" class\x3d"attach-warranty-input" name\x3d"useABBHandler" value\x3d"1" /\x3e');var h=f.find("input[name^\x3d'offeringID']").length+
1,k=a.$(m.ATC_QUANTITY).val()||1,g="quantity."+h,l="asin."+h;f.find('input[name\x3d"'+g+'"]').remove();f.find('input[name\x3d"'+l+'"]').remove();f.append('\x3cinput type\x3d"hidden" id\x3d"'+g+'" name\x3d"'+g+'" value\x3d"'+k+'" class\x3d"attach-warranty-input" /\x3e');f.append('\x3cinput type\x3d"hidden" id\x3d"'+l+'" name\x3d"'+l+'" value\x3d"'+b+'" class\x3d"attach-warranty-input" /\x3e');f.append('\x3cinput type\x3d"hidden" id\x3d"offeringID.'+h+'" name\x3d"offeringID.'+h+'" value\x3d"'+e+'" class\x3d"attach-warranty-input"/\x3e');
b=f.find('input[name\x3d"itemCount"]');0===b.length?f.append('\x3cinput type\x3d"hidden" name\x3d"itemCount" value\x3d"'+h+'"\x3e'):b[0].value=h;a.$("#atch__bl").length&&d.createBaseLinkFormFields(h+1,f)}};b.clearWarrantyFromATCForm=function(){c.getAtcForm().find(m.ATC_WARRANTY).remove()};b.load=function(b){var e;c.elementExists(m.JSON_DATA)&&(e=c.unescapeJson(a.$(m.JSON_DATA).val()),e=JSON.parse(e));if(!e)return c.reject(c.FailureModes.RESUBMIT_BUY_BOX,{count:"ATTACH_DSS_WARRANTY_LOAD_FAILURE"});
if(e.triggerUpsellImageExperiment){var d=a.$.param({weblabs:["WTY_221862"]},!0);a.$.post("/gp/product/features/aloha-ppd/getTreatmentAndRecordWeblabs.html",d)}var d="",f=e.baseASIN,h="dp_atch_dss_w_lm_"+f+"_"+e.asin,g="dp_atch_dss_w_r_"+f+"_"+e.asin,f="dp_atch_dss_w_lm_"+f+"_"+e.asin,k=a.$("#stringTranslation-si-warranty-title").val(),z=a.$("#stringTranslation-si-accident-protection").val(),n=a.$("#stringTranslation-si-from").val(),q=a.$("#stringTranslation-si-rating-out-of-5-stars").val(),y=a.$("#stringTranslation-item-added-to-cart").val(),
l=a.$("#stringTranslation-desktop-attach-accessory-failed-add-to-cart").val(),r=a.$("#stringTranslation-desktop-attach-accessory-retry").val(),A=a.$("#stringTranslation-si-add-coverage").val(),u=a.$("#stringTranslation-si-no-thanks").val(),B=a.$("#stringTranslation-services-bundle-detail-link").val(),d=d+('   \x3cdiv id\x3d"attach-warranty-pane" class\x3d"a-section"\x3e\n       \x3cdiv id\x3d"attach-warranty" class\x3d"a-section attach-sidesheet-card"\x3e\n           \x3cinput type\x3d"hidden" name\x3d"" value\x3d"'+
e.asin+'" id\x3d"attach-warranty-asin"\x3e\n           \x3ch1 class\x3d"a-size-medium a-spacing-none a-color-base a-text-center"\x3e'+k+'\x3c/h1\x3e\n           \x3chr class\x3d"a-spacing-base a-spacing-top-small a-divider-normal attach-warranty-divider"\x3e\n           \x3cdiv class\x3d"a-row a-spacing-micro"\x3e\n');null!==e.warrantyUpsellImage&&e.triggerUpsellImageExperiment&&(d+='                \x3cdiv class\x3d"a-row a-span-last"\x3e\n                    \x3cimg id\x3d"attach-sheet-warranty-upsell-image" src\x3d"" data-image-url\x3d"'+
e.warrantyUpsellImage+'" class\x3d"attach-warranty-upsell-image"\x3e\n                \x3c/div\x3e\n                \x3cdiv class\x3d"a-row a-spacing-micro"\x3e\n');null!==e.thumbImage&&(d+='                \x3cdiv class\x3d"a-column a-span2"\x3e\n                    \x3cimg id\x3d"attach-sheet-warranty-image" src\x3d"" data-image-url\x3d"'+e.thumbImage+'" class\x3d"attach-accessory-image"\x3e\n                \x3c/div\x3e\n');d+='                \x3cdiv class\x3d"a-column a-span10 a-span-last"\x3e\n                    \x3ca class\x3d"a-size-large a-spacing-micro a-link-normal a-color-base" id\x3d"attach-warranty-displayTitle" target\x3d"_blank" rel\x3d"noopener" href\x3d"/dp/'+
e.asin+"/ref\x3d"+h+'"\x3e\n                        \x3cstrong\x3e'+(null!==e.displayTitle?e.displayTitle:z.replace("${brandName}",e.brandName))+'\x3c/strong\x3e\n                    \x3c/a\x3e\n                    \x3cbr\x3e\n                    \x3cspan class\x3d"a-size-base a-color-secondary"\x3e'+n+" "+e.merchantName+"\x3c/span\x3e\n";Number(e.averageRating)&&Number(e.numReviews)&&Number(e.numFullStars)&&"boolean"===typeof e.hasHalfStar&&(h=q.replace("${averageRating}",e.averageRating),d+='                    \x3cdiv class\x3d"a-icon-row a-spacing-micro"\x3e\n                        \x3ca class\x3d"a-link-normal" href\x3d"/product-reviews/'+
e.asin+"/ref\x3d"+g+'?ie\x3dUTF8\x26amp;showViewpoints\x3d1"\x3e\n                            \x3ci class\x3d"a-icon a-icon-star a-star-'+e.numFullStars+(e.hasHalfStar?"-5":"")+'"\x3e\x3cspan class\x3d"a-icon-alt"\x3e'+h+'\x3c/span\x3e\x3c/i\x3e\n                        \x3c/a\x3e\n                        \x3ca class\x3d"a-link-normal" href\x3d"/product-reviews/'+e.asin+"/ref\x3d"+g+'?ie\x3dUTF8\x26amp;showViewpoints\x3d1"\x3e\n                            '+e.numReviews+"\n                        \x3c/a\x3e\n                    \x3c/div\x3e\n");
null!==e.buyingPriceAmount&&(d+='                    \x3cinput id\x3d"attach-accessory-price-warranty-amount" type\x3d"hidden" value\x3d"'+e.buyingPriceAmount+'"\x3e\n');d+='                    \x3cspan id\x3d"attach-accessory-price-warranty" class\x3d"a-size-large a-color-base attach-warranty-price"\x3e'+e.formattedBuyingPrice+'\x3c/span\x3e\n                \x3c/div\x3e\n            \x3c/div\x3e\n            \x3cdiv class\x3d"a-row"\x3e\n                \x3cdiv class\x3d"a-column a-span12"\x3e\n                    \x3cdiv id\x3d"warrantyBulletRowWrapper" class\x3d"a-section"\x3e\n                        \x3cdiv class\x3d"a-row a-spacing-micro"\x3e\n                            \x3cul class\x3d"a-unordered-list a-vertical a-spacing-none"\x3e\n';
for(g=0;g<e.bulletPoints.length;g++)d+='                                \x3cli\x3e\x3cspan class\x3d"a-list-item"\x3e'+e.bulletPoints[g].text+"\x3c/span\x3e\x3c/li\x3e\n";d+='                            \x3c/ul\x3e\n                        \x3c/div\x3e\n                        \x3cdiv id\x3d"attachWarrantyButtonWrapper" class\x3d"a-section a-box-inner a-color-alternate-background"\x3e\n                            \x3cdiv id\x3d"attachWarrantyButtonInnerWrapper" class\x3d"a-section a-box-inner"\x3e\n                                \x3cdiv id\x3d"attach_add_accessory_alert_warranty" class\x3d"a-box a-alert-inline a-alert-inline-success aok-hidden attach_add_accessory_alert"\x3e\n                                    \x3cdiv class\x3d"a-box-inner a-alert-container"\x3e\n                                        \x3ci class\x3d"a-icon a-icon-alert"\x3e\x3c/i\x3e\n                                        \x3cdiv class\x3d"a-alert-content"\x3e\n                                            \x3cspan class\x3d"a-size-base a-color-success"\x3e'+
y+'\x3c/span\x3e\n                                        \x3c/div\x3e\n                                    \x3c/div\x3e\n                                \x3c/div\x3e\n                                \x3cdiv id\x3d"attach_add_accessory_error_warranty" class\x3d"a-box a-alert-inline a-alert-inline-error aok-hidden attach_add_accessory_alert" aria-live\x3d"assertive" role\x3d"alert"\x3e\n                                    \x3cdiv class\x3d"a-box-inner a-alert-container"\x3e\n                                        \x3ci class\x3d"a-icon a-icon-alert"\x3e\x3c/i\x3e\n                                        \x3cdiv class\x3d"a-alert-content"\x3e\n                                            \x3cspan class\x3d"a-size-base"\x3e\n                                                '+
l+'\x3cbr\x3e\n                                            \x3c/span\x3e\n                                            \x3ca class\x3d"a-link-normal attach-add-to-cart-retry" href\x3d"#"\x3e\n                                                '+r+'\n                                            \x3c/a\x3e\n                                        \x3c/div\x3e\n                                    \x3c/div\x3e\n                                \x3c/div\x3e\n                                \x3cspan id\x3d"attach_add_accessory_spinner_warranty" class\x3d"a-spinner a-spinner-small attach-spinner aok-hidden"\x3e\x3c/span\x3e\n                                \x3cdiv class\x3d"a-section attach-warranty-button-row"\x3e\n                                    \x3cdiv class\x3d"a-button-stack"\x3e\n                                        \x3cspan id\x3d"attachSiAddCoverage" class\x3d"a-button a-button-primary"\x3e\n                                            \x3cspan class\x3d"a-button-inner"\x3e\n                                                \x3cbutton id\x3d"attachSiAddCoverage-announce" data-asin\x3d"'+
e.asin+'" data-offering-id\x3d"'+e.oid+'" class\x3d"a-button-text" type\x3d"button"\x3e\n                                                    '+A+'\n                                                \x3c/button\x3e\n                                            \x3c/span\x3e\n                                        \x3c/span\x3e\n                                        \x3cspan id\x3d"attachSiNoCoverage" class\x3d"a-button"\x3e\n                                            \x3cspan class\x3d"a-button-inner"\x3e\n                                                \x3cbutton id\x3d"attachSiNoCoverage-announce" class\x3d"a-button-text" type\x3d"button"\x3e\n                                                    '+
u+'\n                                                \x3c/button\x3e\n                                            \x3c/span\x3e\n                                        \x3c/span\x3e\n                                    \x3c/div\x3e\n                                \x3c/div\x3e\n                            \x3c/div\x3e\n                        \x3c/div\x3e\n                    \x3c/div\x3e\n                \x3c/div\x3e\n            \x3c/div\x3e\n            \x3ca class\x3d"a-link-normal" target\x3d"_blank" rel\x3d"noopener" href\x3d"/dp/'+
e.asin+"/ref\x3d"+f+'"\x3e\n                '+B+"\n            \x3c/a\x3e\n        \x3c/div\x3e\n    \x3c/div\x3e\n";b.$container.append(d)};b.onAttachAddBaseToCart=function(a){a.always(b.clearWarrantyFromATCForm)};b.setup=function(d){a.$(m.PANE).hide();var e=a.$(m.PANE_IMAGE).attr("data-image-url");a.$(m.PANE_IMAGE).attr("src",e);e=a.$(m.PANE_UPSELL_IMAGE).attr("data-image-url");a.$(m.PANE_UPSELL_IMAGE).attr("src",e);a.$(m.PANE_ADD_BUTTON).click(function(){var e=a.$(this).find("button"),h=e.attr("data-asin"),
e=e.attr("data-offering-id");b.appendWarrantyToATCForm(h,e);c.submitATCForm();f.logWarrantyAddToCart(b.getWarrantyLoggingPayload());d.next()});a.$(m.PANE_NO_BUTTON).click(function(){c.submitATCForm();d.next()});a.off("attach:add-base-to-cart",b.onAttachAddBaseToCart);a.on("attach:add-base-to-cart",b.onAttachAddBaseToCart)};b.show=function(){a.$(m.PANE).fadeIn(400,b.setFocus);f.logWarrantyImpression(b.getWarrantyLoggingPayload())};b.hide=function(){a.$(m.PANE).fadeOut()};b.setFocus=function(){a.$(m.PANE_WARRANTY_TITLE).get(0).focus()};
return b});"use strict";k.when("A","attach-common","attach-weblabs","attach-maple","attach-logging","attach-variant-registration").register("attach-desktop-accessories-pane",function(a,c,f,d,h,r){var b={name:"accessories"},m=!0,v=!1,e,w=!1,t=!1,x=b.Endpoints={RENDER:"/gp/product/features/aloha-ppd/udp-ajax-handler/attach-render-desktop.html",GET_CART_DESCRIPTION:"/gp/product/features/aloha-ppd/udp-ajax-handler/attach-get-cart-description.html",ADD_ACCESSORY_TO_CART:"/gp/product/features/aloha-ppd/udp-ajax-handler/attach-add-to-cart.html",
PROCEED_TO_CHECKOUT:"/gp/cart/desktop/go-to-checkout.html?proceedToCheckout\x3dProceed"},g=b.Selectors={BASE_ASIN:"#attach-baseAsin",QUANTITY:"#quantity",ACCESSORY_ASIN_LIST:"#attach-asin-list",MARKETPLACE_ID:"#attach-marketplaceId",LANGUAGE_OF_PREFRENCE:"#attach-languageOfPreference",PANE:"#attach-accessory-pane",PANE_CLOSE_BUTTON:"#attach-close_sideSheet-link",PANE_CART_BASE_ALERT_IMAGE_AREA:"#attach-added-to-cart-alert-and-image-area",PANE_CART_BASE_ALERT:"#attachDisplayAddBaseAlert",PANE_CART_BASE_SUCCESS_ALERT:"#attachAddBaseItemSuccessAlert",
PANE_CART_BASE_ERROR_ALERT:"#attachAddBaseItemErrorAlert",PANE_CART_BASE_INITIAL_IMAGE:"#attach-sheet-view-base-product-image",PANE_CART_BASE_HUC_IMAGE:".huc-image-wrapper",PANE_CART_BLOCK:".attach-primary-atc-confirm-box",PANE_CART_BLOCK_INNER:"#attach-added-to-cart-message",PANE_CART_BLOCK_SUBTOTAL_LABEL:"#attach-accessory-cart-total-string",PANE_CART_BLOCK_SUBTOTAL_PRICE:"#attach-accessory-cart-subtotal",PANE_CART_BLOCK_CORE_FREE_SHIPPING_MESSAGE:"#attach-core-free-shipping-message",PANE_CART_BLOCK_PROCEED_TO_CHECKOUT:"#attach-accessory-proceed-to-checkout-text",
PANE_CART_SPINNER:"#attach-add-to-cart-message-spinner",PANE_VIEW_CART_BUTTON:"#attach-sidesheet-view-cart-button",PANE_CHECKOUT_BUTTON:"#attach-sidesheet-checkout-button",PANE_HUC_MESSAGE:".attach-add-to-cart-message-card",PANE_ACCESORIES_CARD:"#attach-accessories",PANE_ACCESSORY_RETRY_BUTTON:".attach-add-to-cart-retry",PANE_ACCESSORY_ADD_DECLARATIVES:'.a-declarative[data-action\x3d"attach-accessory-add"]',PANE_ACCESSORY_IMAGE:".attach-accessory-image",PANE_ACCESSORY_ASIN:".attach-accessory-asin",
PANE_ACCESSORY_ADD_BUTTON_PREFIX:"#attach_add_accessory_button_",PANE_ACCESSORY_ADD_SPINNER_PREFIX:"#attach_add_accessory_spinner_",PANE_ACCESSORY_ADD_SUCCESS_PREFIX:"#attach_add_accessory_alert_",PANE_ACCESSORY_ADD_ERROR_PREFIX:"#attach_add_accessory_error_",PANE_ACCESSORY_FIRST_ASIN:"#attach_accessory_dp_1",PANE_CATEGORIZED_ACCESSORIES_CARD:"#attach-categorized-accessories",PANE_ACCESSORY_TITLE:".attach-accessory-title",PANE_ACCESSORY_TILE_ITEM:".attach-accessory-tile",PANE_ACCESSORY_CAROUSEL:"#attach-accessories .a-carousel-container",
PANE_ACCESSORY_CARD:"#attach-accessories.card-expandable",PANE_ACCESSORY_CARD_SEE_MORE:".card-toggle-see-more",PANE_ACCESSORY_CARD_SEE_LESS:".card-toggle-see-less",PANE_ACCESSORY_CARD_PEEK_CONTENT:".card-peek-content",PANE_ACCESSORY_CARD_EXPAND_CONTENT:".card-expand-content",PANE_MAPLE_SLOT:"#maple-dss-slot",PANE__DATA_CATEGORY_VIEW:"categoryView",PANE__DATA_ASIN_INDEX:"asinindex",PANE_ACCESSORY_COUPON:".attach-accessory-coupon",PANE_ACCESSORY_COUPON_PREFIX:"#attach-accessory-coupon-",PANE_ACCESSORY_COUPON_UNCLIPPED_CLASS:".attach-coupon-unclipped",
PANE_ACCESSORY_COUPON_CLIPPED_CLASS:".attach-coupon-clipped",PANE_ACCESSORY_COUPON_ERROR_CLASS:".attach-coupon-error",PANE_ACCESSORY_COUPON_BADGE_UNCLIPPED_CLASS:".attach-coupon-badge-unclipped",PANE_ACCESSORY_COUPON_BADGE_CLIPPED_CLASS:".attach-coupon-badge-clipped",DEBUG_IS_DEBUG:"#attach-debug-isDebug",DEBUG_QUERY_STRING:"#attach-debug-queryString"},p=b.AccessoryAddStatus={INITIAL:0,ADDING:1,SUCCESS:2,ERROR:3};b.setShouldIncludeMaple=function(a){v=a};b.load=function(b){k.now("attach-external-atc-interceptor").execute(function(a){e=
a});a.trigger("LOADED_ACCESSORIES_PANE_SUCCESSFULLY");var n=a.$.Deferred(),q,y;k.now("dp-util-cookie").execute(function(b){b&&b("session-id")!==a.$("#attach-sessionId").val()&&c.rejectPromise(n,c.FailureModes.TRANSITION_TO_HUC,{count:"ATTACH_DSS_INVALID_SESSION_ID"})});f.isWeblabTriggeringConsolidationEnabled()?(q={attachAccessoryAsinList:a.$(g.ACCESSORY_ASIN_LIST).val(),marketplaceId:a.$(g.MARKETPLACE_ID).val(),asin:a.$(g.BASE_ASIN).val(),deviceType:"desktop",attachWeblabsToTrigger:[]},f.isAttachDebugParametersEnabled()&&
(q.isDebug=a.$(g.DEBUG_IS_DEBUG).val(),q.queryString=a.$(g.DEBUG_QUERY_STRING).val()),q=a.$.param(q,!0)):q=a.$.param({attachAccessoryAsinList:a.$(g.ACCESSORY_ASIN_LIST).val(),marketplaceId:a.$(g.MARKETPLACE_ID).val(),asin:a.$(g.BASE_ASIN).val(),deviceType:"desktop",attachWeblabsToTrigger:f.getWeblabsToTriggerClientSide()},!0);q=a.$.post(x.RENDER,q);v&&(c.isCurrencyOfPreferenceApplied()&&d.suppressMathBox(),y=d.loadBannerHTML());a.$.when(q,y).done(function(e,d){var f=a.$(e[0].trim()),q=!f.is(g.PANE),
f=0===f.find(g.PANE_ACCESSORY_ASIN).length;q||f?c.rejectPromise(n,c.FailureModes.TRANSITION_TO_HUC,{count:["ATTACH_DSS_RENDER_FAILURE","ATTACH_DSS_RENDER_FAILURE_INVALID_HTML"]}):(b.$container.append(a.$(e[0]).get(0)),d&&0<d.trim().length&&(d=a.$(d),e=d.not("script"),d=d.filter("script"),e.insertAfter(g.PANE_ACCESORIES_CARD),e.wrap('\x3cdiv id\x3d"maple-dss-slot"\x3e\x3cdiv id\x3d"maple-dss-card" class\x3d"a-section attach-sidesheet-card"\x3e\x3c/div\x3e\x3c/div\x3e'),d.each(function(){a.$.globalEval(this.innerHTML)}),
h.logCount("ATTACH_DSS_MAPLE_RENDERED")),n.resolve())}).fail(function(){c.rejectPromise(n,c.FailureModes.TRANSITION_TO_HUC,{count:"ATTACH_DSS_RENDER_FAILURE"})});return n.promise()};b.onAttachAddBaseToCart=function(a){m=!1;a.pipe(b.handleAddBaseAndGetCartDescription).pipe(c.pipeJSON).pipe(b.handleCartDescription).fail(function(a,d){b.sheet.fail(a||c.FailureModes.ERROR_500,d)})};b.runOnceSetup=function(){w||(w=!0,a.declarative("attach-accessory-add","click",function(c){var d=c.$currentTarget,e=c.data,
f=e.a,e=e.oid;c=!0===a.$(g.PANE_CATEGORIZED_ACCESSORIES_CARD).data(g.PANE__DATA_CATEGORY_VIEW)?a.$(c.$target).data(g.PANE__DATA_ASIN_INDEX):a.$(g.PANE_ACCESSORY_ADD_DECLARATIVES).index(d);b.addAccessoryToCart(f,e,c)}))};b.setup=function(c){b.runOnceSetup();a.$(g.PANE).hide();b.sheet=c;a.off("attach:add-base-to-cart",b.onAttachAddBaseToCart);a.on("attach:add-base-to-cart",b.onAttachAddBaseToCart);a.$(g.PANE_VIEW_CART_BUTTON).click(b.viewCart);a.$(g.PANE_CHECKOUT_BUTTON).click(b.proceedToCheckout);
a.$(g.PANE_ACCESSORY_RETRY_BUTTON).click(function(){var c=a.$(this).attr("data-asin"),d=a.$(this).attr("data-oid"),e=a.$(this).attr("data-idx");b.addAccessoryToCart(c,d,e)});a.$(g.PANE_CLOSE_BUTTON).appendTo(g.PANE_CART_BLOCK).click(c.next);a.$(g.PANE_ACCESSORY_IMAGE).each(function(){a.$(this).attr("src",a.$(this).attr("data-image-url"))});f.isShowAccessoryCouponsDssEnabled()&&b.initializeCoupons()};b.show=function(){m&&c.submitATCForm();a.$(g.PANE).css({opacity:0}).show().animate({opacity:1},500,
"linear",b.setFocus);var d=a.$(g.PANE_CART_BLOCK_INNER);d.find("div").addClass("aok-hidden");d.append(a.$(g.PANE_CART_SPINNER).removeClass("aok-hidden"));b.initializeAccessoriesDisplay();k.now("attach-categorized-cards").execute(function(a){a!==u&&a.initializeCategorizedCards()})};b.hide=function(){a.$(g.PANE).hide();a.$(g.PANE_CART_SPINNER).addClass("aok-hidden");a.$(g.PANE_HUC_MESSAGE).remove();a.$(g.PANE_ACCESSORY_ASIN).each(function(c,d){(d=a.$(d).data(g.PANE__DATA_ASIN_INDEX))&&(c=d);b.updateAccessoryStatus(c,
p.INITIAL)});a.trigger("RESET_SECONDARY_SIDE_SHEET_MODULE");e&&e.unloadAttachModule();a.trigger("aloha:detailPage:reappear");m=!0};b.setFocus=function(){a.$(g.PANE_ACCESSORY_FIRST_ASIN).length&&a.$(g.PANE_ACCESSORY_FIRST_ASIN).get(0).focus()};b.viewCart=function(){h.logCount("ATTACH_DSS_CART_BUTTON_CLICK");document.location=""};b.proceedToCheckout=function(){h.logCount("ATTACH_DSS_CHECKOUT_CLICK");document.location=t?x.PROCEED_TO_CHECKOUT+"\x26cartInitiateId\x3d"+t+"\x26ref_\x3ddp_atch_dss_proceed":
x.PROCEED_TO_CHECKOUT+"\x26ref_\x3ddp_atch_dss_proceed"};b.updateNavCartDisplayQuantity=function(c){var b=Number(c);c=isNaN(b)?"":100>b?c:"99+";a.$("#nav-cart-count").toggleClass("nav-cart-0",0===b).toggleClass("nav-cart-1",1<=b&&10>b).toggleClass("nav-cart-10",10<=b&&20>b).toggleClass("nav-cart-20",20<=b&&100>b).toggleClass("nav-cart-100",100<=b).text(c)};b.handleAddBaseAndGetCartDescription=function(d){d=a.$(d);b.renderHUCFeedback(d);b.renderBaseAddStatusIcon(d);if(e)try{var n=a.$(g.PANE_ACCESSORY_ASIN).map(function(){return this.value}).get();
e.loadAttachModule(n)}catch(f){k.logError(f,"Could not update ABB/DSS external interceptor: ","ERROR","attach-desktop-accessories-pane")}n={marketplaceId:a.$(g.MARKETPLACE_ID).val(),asin:a.$(g.BASE_ASIN).val(),languageOfPreference:a.$(g.LANGUAGE_OF_PREFRENCE).val(),customerId:a.$("#attach-customerId").val(),sessionId:a.$("#attach-sessionId").val()};return a.$.post(x.GET_CART_DESCRIPTION,n).pipe(null,function(a,b,d){k.logError(Error(b),"AJAX cart description call failed: ","ERROR","attach-desktop-accessories-pane");
return c.reject(null,{count:"ATTACH_DSS_GET_CART_DESCRIPTION_AJAX_FAILURE"})})};b.handleCartDescription=function(e){try{if(isNaN(parseInt(e.totalPrice))||isNaN(parseInt(e.itemQuantity))||!a.$.isArray(e.includedAsins)||0===e.formattedTotalPrice.trim().length||0===e.cartSubtotalString.trim().length||0===e.itemQuantityString.trim().length)throw Error("Received invalid cart description");b.updateNavCartDisplayQuantity(e.itemQuantity);a.$(g.PANE_CART_BLOCK_SUBTOTAL_LABEL).html(e.cartSubtotalString);a.$(g.PANE_CART_BLOCK_SUBTOTAL_PRICE).html(e.formattedTotalPrice);
a.$(g.PANE_CART_BLOCK_PROCEED_TO_CHECKOUT).html(e.itemQuantityString);a.$("#attach-customerId").val()&&k.when("attach-preinitiate-checkout").execute(function(a){t=a.getCartInitiateId();a.preinitiateCheckout(t)});e.coreFreeShippingMessage&&a.$(g.PANE_CART_BLOCK_CORE_FREE_SHIPPING_MESSAGE).html(e.coreFreeShippingMessage);v&&d.updateMathBox(Number(e.totalPrice));a.$(g.PANE_CART_BLOCK_INNER).find("div").removeClass("aok-hidden");a.$(g.PANE_CART_SPINNER).addClass("aok-hidden");setTimeout(b.revealHUCFeedback,
200);k.when("EWC").execute(function(a){a.refresh()});return e}catch(n){return k.logError(n,"Could not process the cart description: ","ERROR","attach-desktop-accessories-pane"),c.reject(null,{count:"ATTACH_DSS_HANDLE_CART_DESCRIPTION_FAILURE"})}};b.updateAccessoryStatus=function(b,c){a.$(g.PANE_ACCESSORY_ADD_BUTTON_PREFIX+b).toggleClass("aok-hidden",c!==p.INITIAL);a.$(g.PANE_ACCESSORY_ADD_SPINNER_PREFIX+b).toggleClass("aok-hidden",c!==p.ADDING);a.$(g.PANE_ACCESSORY_ADD_SUCCESS_PREFIX+b).toggleClass("aok-hidden",
c!==p.SUCCESS);a.$(g.PANE_ACCESSORY_ADD_ERROR_PREFIX+b).toggleClass("aok-hidden",c!==p.ERROR);a.$("#tile-add-accessory-badge-"+b).toggleClass("aok-hidden",c!==p.SUCCESS);a.$("#attach-accessory-tile-"+b).toggleClass("in-cart",c===p.SUCCESS)};b.addAccessoryToCart=function(e,d,f){d={marketplaceId:a.$(g.MARKETPLACE_ID).val(),asin:a.$(g.BASE_ASIN).val(),customerId:a.$("#attach-customerId").val(),sessionId:a.$("#attach-sessionId").val(),accessoryItemAsin:e,accessoryItemOfferingId:d,languageOfPreference:a.$(g.LANGUAGE_OF_PREFRENCE).val(),
accessoryItemQuantity:a.$(g.QUANTITY).val(),accessoryItemPrice:a.$("#attach-accessory-base-price-"+f).val(),accessoryMerchantId:a.$("#attach-accessory-merchantId-"+f).val(),accessoryProductGroupId:a.$("#attach-accessory-product-category-code-"+f).val()};b.updateAccessoryStatus(f,p.ADDING);a.$.post(x.ADD_ACCESSORY_TO_CART,d).pipe(c.pipeJSON).pipe(b.handleCartDescription).pipe(function(d){if(-1===a.$.inArray(e,d.includedAsins))return c.reject(null,{count:"ATTACH_DSS_ADD_ACCESSORY_NOT_IN_CART"});b.updateAccessoryStatus(f,
p.SUCCESS);h.logAccessoryAddToCart(b.getAccessoryLoggingData(f));a.trigger("UPSELL_ASIN_ADDED_TO_CART",f);k.when("EWC").execute(function(a){a.refresh()})}).fail(function(){h.logCount("ATTACH_DSS_ADD_ACCESSORY_FAILURE");b.updateAccessoryStatus(f,p.ERROR);a.trigger("UPSELL_ASIN_NOT_ADDED_TO_CART",f)})};b.revealHUCFeedback=function(){var b=a.$(g.PANE_HUC_MESSAGE);if(b.hasClass("aok-hidden")){b.css({position:"absolute",top:0}).removeClass("aok-hidden");var c=b.children().height();0<c&&b.css({marginTop:-1*
(c+4)+"px",position:"initial"}).animate({marginTop:"14px"},800)}};b.renderHUCFeedback=function(b){var d=b.find("#hlb-ship-message");b=a.$().add(b.find("#huc-v2-message-group")).add(b.find("#hlb-imb"));f.isCoreFreeShippingMessageEnabled()&&c.elementExists(d)&&a.$(g.PANE_CART_BLOCK_CORE_FREE_SHIPPING_MESSAGE).html(d.html());0<b.length&&(d=a.$("\x3cdiv class\x3d'attach-sidesheet-card attach-add-to-cart-message-card aok-hidden'\x3e\x3c/div\x3e"),d.append(b),d.insertAfter(g.PANE_CART_BLOCK),d.find(".a-declarative a").unwrap(),
d.find(".a-declarative span").removeClass("a-color-link huc-cursor-pointer").unwrap(),d.find(".sc-action-quantity").hide(),(d=b.find(".a-alert-heading").text())&&h.logDSSWarningMessage(d))};b.renderBaseAddStatusIcon=function(b){var d;c.elementExists(b.find("#huc-v2-order-row-confirm-text"))?d=b.find("#huc-v2-order-row-confirm-text").hasClass("a-color-error"):c.elementExists(b.find("#hl-confirm-text"))&&(d=b.find("#hl-confirm-text").hasClass("a-alert-warning"));d=(d?a.$(g.PANE_CART_BASE_ERROR_ALERT):
a.$(g.PANE_CART_BASE_SUCCESS_ALERT)).clone().prop("id","attachDisplayAddBaseAlert");a.$(g.PANE_CART_BASE_ALERT).remove();a.$(g.PANE_CART_BASE_ALERT_IMAGE_AREA).prepend(d);d=b.find(".huc-v2-order-row-image").clone();c.elementExists(d)||(d=b.find(".hlb-product-image").clone());if(1<d.length){d=d.first();var e=a.$('input[name^\x3d"asin"].attach-warranty-input');0===e.length&&(e=a.$('.abbListItem.mbb__r input[name^\x3d"asin"]'));if(c.elementExists(e))for(var f=0;f<e.length;f++){var h=e[f].value,k=b.find("#huc-v2-order-row-item-"+
h);if(k.length){b=c.elementExists(k)?k.find(".huc-v2-order-row-image"):b.find(".hlb-item-link.hlb-asin-"+h+" \x3e img");d=d.add(b.clone());break}}}a.$(g.PANE_CART_BASE_HUC_IMAGE).remove();a.$(g.PANE_CART_BASE_INITIAL_IMAGE).hide().parent().append(d);d.wrap('\x3cdiv class\x3d"huc-image-wrapper"\x3e\x3c/div\x3e')};b.getAccessoryLoggingData=function(b){return{asin:a.$("#attach-accessory-asin-"+(parseInt(b)+1)).val(),index:b,priceFormatted:a.$("#attach-accessory-price-"+b+" \x3e .a-offscreen").text(),
priceDecimal:parseFloat(a.$("#attach-accessory-base-price-"+b).val())||null,currencySymbol:a.$("#attach-accessory-base-currency-symbol-"+b).val()||null,couponDecimal:parseFloat(a.$("#attach-accessory-coupon-benefit-amount-"+b).val())||null,couponType:a.$("#attach-accessory-coupon-benefit-type-"+b).val()||null}};b.createAccessoryImpressions=function(){var c=[];a.$(g.PANE_ACCESSORY_ASIN).parent().each(function(d,e){e=a.$(e);if(e.is(":hidden")||"hidden"===e.css("visibility")||e.prop("data-accessory-seen"))return null;
e.prop("data-accessory-seen",!0);c.push(b.getAccessoryLoggingData(d))});return c};b.resetAccessoryImpressions=function(){a.$(g.PANE_ACCESSORY_ASIN).parent().removeProp("data-accessory-seen")};b.initializeAccessoriesDisplay=function(){b.initializeAccessoriesCards();b.initializeAccessoriesTiles();a.animationFrameDelay(function(){b.resetAccessoryImpressions();h.logAccessoryImpressions(b.createAccessoryImpressions())})};b.initializeAccessoriesCards=function(){a.$(g.PANE_ACCESSORY_CARD).each(function(){var c=
a.$(this),d=c.find(g.PANE_ACCESSORY_CARD_SEE_MORE),e=c.find(g.PANE_ACCESSORY_CARD_SEE_LESS),f=c.find(g.PANE_ACCESSORY_CARD_EXPAND_CONTENT);d.show();e.hide();f.hide();c.removeProp("data-card-expanded");c.removeProp("data-card-previously-expanded");d.click(function(){d.hide();e.show();f.slideDown(400);c.prop("data-card-expanded",!0);c.parent().animate({scrollTop:c.get(0).offsetTop-30},400);c.prop("data-card-previously-expanded")||(c.prop("data-card-previously-expanded",!0),h.logAccessoryImpressions(b.createAccessoryImpressions()))});
e.click(function(){e.hide();d.show();f.slideUp(400);c.prop("data-card-expanded",!1)})})};b.initializeAccessoriesTiles=function(){k.when("a-truncate").execute(function(b){a.$(g.PANE_ACCESSORY_TITLE).each(function(){b.get(this).update()});a.$(g.PANE_ACCESSORY_TILE_ITEM).hover(function(){var c=a.$(this).find(g.PANE_ACCESSORY_TITLE);c.length&&b.get(c.get()).update()})})};b.initializeAccessoriesCarousel=function(){k.when("a-truncate","a-carousel-framework").execute(function(c,d){if(a.$(g.PANE_ACCESSORY_CAROUSEL).length){a.$(g.PANE_ACCESSORY_TITLE).each(function(){c.get(this).update()});
d.createAll();var e=d.getCarousel(a.$(g.PANE_ACCESSORY_CAROUSEL));e&&(e.attachViewedPages=[1],e.gotoPage(1,{animationDuration:1}),a.on("a:carousel:attach-carousel:change:animating",function(a){a.newValue||(a=e.getAttr("pageNumber"),-1===e.attachViewedPages.indexOf(a)&&(e.attachViewedPages.push(a),h.logAccessoryImpressions(b.createAccessoryImpressions())))}))}})};b.initializeCoupons=function(){var c;a.on("a:popover:positionUpdated:attach-coupon-popover",b.handleCouponPopoverPositionUpdated);a.on("a:popover:beforeShow:attach-coupon-popover",
function(d){d.popover.$trigger.parents(g.PANE_ACCESSORY_TILE_ITEM).addClass("hover");c=b.createCouponPopoverPositionHandler(d);a.$(l).bind("scroll",c);a.$(g.PANE+" \x3e .a-scroller").bind("scroll",c)});a.on("a:popover:afterHide:attach-coupon-popover",function(b){b.popover.$trigger.parents(g.PANE_ACCESSORY_TILE_ITEM).removeClass("hover");a.$(l).unbind("scroll",c);a.$(g.PANE+" \x3e .a-scroller").unbind("scroll",c)});a.declarative("attach-coupon-checkbox","change",function(c){var d=c.data,e=c.$currentTarget.parents(g.PANE_ACCESSORY_COUPON);
d&&d.ajaxClaimUrl?a.$.get(d.ajaxClaimUrl).done(function(){b.handleCouponClaimSuccess(e,d.accessoryItemIndex)}).fail(function(a,c,d){k.logError(Error(d),"Could not clip coupon: ","ERROR","attach-desktop-accessories-pane");b.handleCouponClaimError(e)}):(k.logError(Error("Coupon claim URL not available"),"Could not clip coupon: ","ERROR","attach-desktop-accessories-pane"),b.handleCouponClaimError(e))})};b.handleCouponPopoverPositionUpdated=function(a){a.popover.$container.css("z-index",6E3)};b.createCouponPopoverPositionHandler=
function(a){return function(){a.popover.updatePosition()}};b.handleCouponClaimSuccess=function(a,c){h.logPromotionClaimed(b.getAccessoryLoggingData(c-1));a.find(g.PANE_ACCESSORY_COUPON_UNCLIPPED_CLASS).addClass("aok-hidden");a.find(g.PANE_ACCESSORY_COUPON_CLIPPED_CLASS).removeClass("aok-hidden");a=a.parents(g.PANE_ACCESSORY_TILE_ITEM);a.length&&(a.find(g.PANE_ACCESSORY_COUPON_BADGE_UNCLIPPED_CLASS).addClass("aok-hidden"),a.find(g.PANE_ACCESSORY_COUPON_BADGE_CLIPPED_CLASS).removeClass("aok-hidden"))};
b.handleCouponClaimError=function(a){a.find(g.PANE_ACCESSORY_COUPON_UNCLIPPED_CLASS).addClass("aok-hidden");a.find(g.PANE_ACCESSORY_COUPON_CLIPPED_CLASS).addClass("aok-hidden");a.find(g.PANE_ACCESSORY_COUPON_ERROR_CLASS).removeClass("aok-hidden")};return b});"use strict";k.when("A","attach-common","attach-weblabs").register("attach-desktop-side-sheet",function(a,c,f){var d={},h=[],k=-1,b,m,v,e,w,t=d.Selectors={PLACEHOLDER:"#attach-dss-placeholder",SHEET:"#attach-desktop-sideSheet",LIGHTBOX:"#attach-popover-lgtbox.attach-popover"};
d.transitionDuration=500;d.onKeyDown=function(a){27===a.which&&d.next()};d.initialize=function(){h=[];c.elementExists(t.SHEET)||c.elementExists(t.LIGHTBOX)||(d.$container=a.$('\x3cdiv id\x3d"attach-desktop-sideSheet" class\x3d"a-section attach-desktop-sideSheet"\x3e\x3c/div\x3e'),d.$container.addClass("aok-hidden"),d.$container.appendTo(t.PLACEHOLDER),e=a.$("\x3cdiv id\x3d'attach-popover-lgtbox' class\x3d'a-declarative attach-popover a-modal' data-action\x3d'a-popover-floating-close' style\x3d'z-index: 1008; opacity: 0.4; cursor: pointer'\x3e\x3c/div\x3e"),
e.hide(),e.appendTo(t.PLACEHOLDER),e.click(d.next));a.$(document).unbind("keydown",d.onKeyDown);a.$(document).keydown(d.onKeyDown);b=function(){};m=function(){};v=!0};d.setFailureHandler=function(a){b=a};d.setCloseHandler=function(a){m=a};d.fail=function(a,c){b(a,c)};d.addPane=function(a){h.push(a)};d.removePane=function(a){a=h.indexOf(a);-1<a&&h.splice(a,1)};d.next=function(){k+1===h.length?(e.hide(),d.$container.animate({right:w},{duration:d.transitionDuration,complete:function(){h[k].hide();k=
-1;m()}}),l.ue&&l.ue.count&&l.ue.count("ATTACH_DSS_CLOSE_ACCESSORY_PANE",(l.ue.count("ATTACH_DSS_CLOSE_ACCESSORY_PANE")||0)+1),a.trigger("HIDE_SIDE_SHEET")):-1!==k&&(h[k].hide(),h[k+1].show(),k+=1)};d.show=function(){if(v){v=!1;var b=a.$.map(h,function(a){return a.load(d)});a.$.when.apply(a.$,b).fail(d.fail).done(function(){a.$.each(h,function(a,b){b.setup(d)});d.show()})}else k=0,h[k].show(),w=d.$container.css("right"),d.$container.removeClass("aok-hidden"),d.$container.animate({right:"0"},d.transitionDuration,
"linear"),e.show(),l.ue&&l.ue.count&&(b=a.$("#attach-customerId").val()?"ATTACH_DSS_SHOW_HAS_CUSTOMER_ID":"ATTACH_DSS_SHOW_NO_CUSTOMER_ID",l.ue.count(b,(l.ue.count(b)||0)+1),b="true"===a.$("#attach-is-prime-member").val()?"ATTACH_DSS_IS_PRIME_MEMBER":"ATTACH_DSS_IS_NOT_PRIME_MEMBER",l.ue.count(b,(l.ue.count(b)||0)+1))};return d});"use strict";k.when("A","attach-common","attach-weblabs","attach-logging","attach-maple","attach-desktop-warranty-pane","attach-desktop-accessories-pane","attach-desktop-side-sheet",
"attach-variant-registration").register("attach-desktop",function(a,c,f,d,h,r,b,m,v){var e={};e.FLAG_USS_VS_DSS=v.getVariantFlag("USS_DESKTOP_DSS_LAUNCH_199700:T1");e.SUPRESS_WARRANTY_PANE=v.getVariantFlag("ATTACH_SUPPRESS_WARRANTY_PANE");var w,t,x=!1,g=l.ue,p=e.Events={ATTACH_ATC_CLICK_NAMESPACE:"click.attachDSS",WARRANTY_SI_CLICK_NAMESPACE:"click.siatc"},u=e.Endpoints={ERROR_500_URL:"/gp/errors/500.html",WARRANTY_SI_CHECK:"/gp/si/util/is-si-with-triggers.html",GET_TREATMENT_AND_RECORD_WEBLABS:"/gp/product/features/aloha-ppd/getTreatmentAndRecordWeblabs.html"},
n=e.Selectors={ADD_TO_CART_BUTTON:"#add-to-cart-button",INSTALLMENTS_BUTTON:"#installments-button",ASIN:"#ASIN",QUANTITY:"#quantity",BASE_ITEM_PRICE_DECIMAL:"#attach-base-product-price",BASE_ITEM_CURRENCY_SYMBOL:"#attach-base-product-currency-symbol",ATTACH_ASIN_LIST:"#attach-asin-list",ATTACH_MARKETPLACE_ID:"#attach-marketplaceId",ATTACH_BASE_ASIN:"#attach-baseAsin",MBB_WARRANTY_ITEM:"#abbWrapper .abbListItem input[type\x3dcheckbox]"},q=e.Classes={ATTACH_DSS_ATC:"attach-dss-atc"};e.initialize=function(){if(!c.elementExists(m.Selectors.PLACEHOLDER)&&
0===f.getWeblabsToTriggerClientSideForEmptyAsinList().length)return!1;e.setupDependencies();e.setupSideSheet();e.setupAddToCartButton()};e.setupDependencies=function(){var b=a.$(n.ATTACH_MARKETPLACE_ID).val();d.initialize(d.FEATURES.DSS,b);d.setPayloadBuilder(function(){return{baseAsin:a.$(n.ASIN).val(),baseItemPriceDecimal:parseFloat(a.$(n.BASE_ITEM_PRICE_DECIMAL).val())||null,baseItemCurrencySymbol:a.$(n.BASE_ITEM_CURRENCY_SYMBOL).val()||null,quantity:Number(a.$(n.QUANTITY).val())||1}});h.initialize();
k.when("attach-external-atc-interceptor").execute(function(a){w=a;w.enableModule()})};e.setupSideSheet=function(){m.initialize();m.setFailureHandler(e.failure);m.setCloseHandler(e.setupAddToCartButton);!e.SUPRESS_WARRANTY_PANE&&c.hasWarranty()?m.addPane(r):b.setShouldIncludeMaple(!0);m.addPane(b)};e.setupAddToCartButton=function(){a.$(document.body).delegate(n.ADD_TO_CART_BUTTON,p.ATTACH_ATC_CLICK_NAMESPACE,e.handleAddToCartClick);a.$(n.ADD_TO_CART_BUTTON).prop("type","button").addClass(q.ATTACH_DSS_ATC);
f.isInstallmentsDssIntegrationEnabled()?(a.$(document.body).delegate(n.INSTALLMENTS_BUTTON,p.ATTACH_ATC_CLICK_NAMESPACE,e.handleAddToCartClick),a.$(n.INSTALLMENTS_BUTTON).prop("type","button").addClass(q.ATTACH_DSS_ATC),a.$(n.INSTALLMENTS_BUTTON).click(function(){g&&g.trigger&&g.trigger("DP_INSTALLMENTS_DSS_231673","T1")})):a.$(n.INSTALLMENTS_BUTTON).click(function(){g&&g.trigger&&g.trigger("DP_INSTALLMENTS_DSS_231673","C")})};e.failure=function(a,b){switch(a){case c.FailureModes.ERROR_500:e.failureError500();
break;case c.FailureModes.RESUBMIT_BUY_BOX:e.failureResubmitBuyBox();break;default:case c.FailureModes.TRANSITION_TO_HUC:e.failureTransitionToHUC()}};e.failureError500=function(){l.location=u.ERROR_500_URL};e.failureResubmitBuyBox=function(){a.$(document.body).undelegate(n.ADD_TO_CART_BUTTON,p.ATTACH_ATC_CLICK_NAMESPACE);a.$(n.ADD_TO_CART_BUTTON).prop("type","submit");f.isInstallmentsDssIntegrationEnabled()&&(a.$(document.body).undelegate(n.INSTALLMENTS_BUTTON,p.ATTACH_ATC_CLICK_NAMESPACE),a.$(n.INSTALLMENTS_BUTTON).prop("type",
"submit"));c.buyButton.click()};e.failureTransitionToHUC=function(){a.$(document.body).undelegate(n.ADD_TO_CART_BUTTON,p.WARRANTY_SI_CLICK_NAMESPACE);f.isInstallmentsDssIntegrationEnabled()&&a.$(document.body).undelegate(n.INSTALLMENTS_BUTTON,p.WARRANTY_SI_CLICK_NAMESPACE);e.failureResubmitBuyBox()};e.handleAddToCartClick=function(b){c.buyButton=a.$(b.target);a.$(document.body).undelegate(n.ADD_TO_CART_BUTTON,p.ATTACH_ATC_CLICK_NAMESPACE);f.isInstallmentsDssIntegrationEnabled()&&(a.$(document.body).undelegate(n.INSTALLMENTS_BUTTON,
p.ATTACH_ATC_CLICK_NAMESPACE),c.getAtcForm().append(c.buyButton.filter("input").clone().attr("type","hidden")));x&&t&&t.fireAndForgetWeblabTrigger("USS_DESKTOP_DSS_169595","C");a.$.when().pipe(e.checkWarranty).pipe(e.checkEmptyAsinListWeblabTriggering).pipe(e.checkFeatureExists).pipe(e.show).fail(e.failure);b.preventDefault();b.stopImmediatePropagation();return!1};e.checkFeatureExists=function(){if(e.shouldSuppressForFeatureNotPresent())return c.reject(c.FailureModes.RESUBMIT_BUY_BOX,{count:"ATTACH_DSS_SUPPRESSED_FEATURE_DOES_NOT_EXIST"})};
e.checkWarranty=function(){if(!e.SUPRESS_WARRANTY_PANE)if(e.shouldSuppressForWarrantyInMbb())m.removePane(r),b.setShouldIncludeMaple(!0),d.logCount("ATTACH_DSS_SUPPRESSED_MBB_WARRANTY_CHECKED",1);else if(c.hasWarranty())return a.$.get(u.WARRANTY_SI_CHECK).pipe(e.handleSICheck,e.handleSIFailure)};e.checkEmptyAsinListWeblabTriggering=function(){if(f.isWeblabTriggeringConsolidationEnabled()){if(f.triggerClientSideWeblabs(),!c.elementExists(n.ATTACH_ASIN_LIST))return c.reject(c.FailureModes.RESUBMIT_BUY_BOX,
{count:"ATTACH_DSS_SUPPRESSED_EMPTY_ASIN_LIST"})}else if(!c.elementExists(n.ATTACH_ASIN_LIST)){var b=f.getWeblabsToTriggerClientSideForEmptyAsinList();if(b&&0<b.length)return b=a.$.param({weblabs:b},!0),a.$.post(u.GET_TREATMENT_AND_RECORD_WEBLABS,b).pipe(function(){return c.reject(c.FailureModes.RESUBMIT_BUY_BOX,{count:"ATTACH_DSS_SUPPRESSED_EMPTY_ASIN_LIST"})})}};e.handleSICheck=function(a){if(!a)return c.reject(c.FailureModes.RESUBMIT_BUY_BOX,{count:"ATTACH_DSS_SUPPRESSED_SI_CHECK_FAILURE"});a.suppressSi&&
(m.removePane(r),b.setShouldIncludeMaple(!0),d.logCount("ATTACH_DSS_SUPPRESSED_SI",1))};e.handleSIFailure=function(){return c.reject(c.FailureModes.RESUBMIT_BUY_BOX,{count:"ATTACH_DSS_SUPPRESSED_SI_CHECK_FAILURE"})};e.shouldSuppressForFeatureNotPresent=function(){return!c.elementExists(m.Selectors.PLACEHOLDER)||!c.elementExists(n.ATTACH_ASIN_LIST)||!c.elementExists(n.ATTACH_MARKETPLACE_ID)||!c.elementExists(n.ATTACH_BASE_ASIN)};e.shouldSuppressForWarrantyInMbb=function(){return 0<a.$(n.MBB_WARRANTY_ITEM).filter(":checked").length};
e.setUssVsDssWeblabToTriggerOnATC=function(a){a&&a.shouldFireAndForgetWeblabTrigger?(k.now("uss-utils").execute(function(a){t=a}),x=!0,t||e.appendUssWeblabToAtcForm()):e.appendUssWeblabToAtcForm()};e.appendUssWeblabToAtcForm=function(){c.getAtcForm().append('\x3cinput type\x3d"hidden" id\x3d"triggerUSSWeblab" name\x3d"triggerUSSWeblab" value\x3d"USS_DESKTOP_DSS_169595"\x3e')};e.show=function(){m.show()};return e});k.when("A","attach-desktop","attach-weblabs","ready").execute("attach-desktop-main",
function(a,c,f){c.FLAG_USS_VS_DSS||(c.initialize(),a.on("a:pageUpdate",a.debounce(function(){c.initialize();a.trigger("attach:dss:initialized")},300)))});"use strict";k.when("A","attach-desktop","dp-util-cookie","cf").execute(function(a,c,f){"000-0000000-8675309"===a.$("#attach-sessionId").val()&&a.$("#attach-sessionId").val(f("session-id"))})});
/* ******** */
(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("DetailPageComparisonChartAssets",""):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("DetailPageFluxComponents",""):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("DetailPageUSSAssets",""):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
